### PR TITLE
Fix : #1111 update python dependencies 

### LINKED ISSUE #1111: Update dependencies
- Lot of python dependencies seems outdated'
Please check https://requires.io/github/Cloud-CV/EvalAI/requirements/?branch=master

### PR DESCRIPTION
**Pull request by the-dagger**
Had a quick look and everything looks in place after making these changes, but I'm still testing if these updates are breaking anything or not.

fixes #1111

### CODE REVIEW

**Comment by the-dagger** [comment]
@deshraj looks good to me now.

**Comment by deshraj** [comment]
@the-dagger I need sometime to test this thoroughly and will let you know about the same soon.

**Comment by RishabhJain2018** [comment]
@the-dagger Can you please resolve the conflicts.

**Comment by the-dagger** [comment]
@RishabhJain2018 Ok, on it

**Comment by the-dagger** [comment]
@RishabhJain2018 Done.
Please squash on your end while merging since I'm away from my machine ATM.

**Comment by deshraj** [comment]
Closing this one as we have decided not to upgrade the dependencies at this point of time.

**Pull request closed without merging**
