### PR TITLE
Settings: Update django project settings

### PR DESCRIPTION
**Pull request by deshraj**
This PR solves the following problems:

- Easy installation instructions (removes the dependency of adding `--settings=settings.dev` for each management command)
- Help to setup celery in an easier way for both local and production environment
- Removes the dependency on three project settings. We can use settings/prod.py now for the staging environment. This will make sure that our staging environment has the exact configuration of the production environment.

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@deshraj There is some error. Please take a look at it.
error

**Comment by deshraj** [comment]
Seems like this is an issue with the Python version. Can you try with python version >=2.7.10?

**Comment by isht3** [comment]
@deshraj I'm using 2.7.12, I'm still getting this error.

**Comment by RishabhJain2018** [comment]
@isht3 Did you try debugging it ?

**Comment by isht3** [comment]
@RishabhJain2018 No, I didn't. I will look into it and will let you know.

**Comment by RishabhJain2018** [comment]
@isht3 Please check what python version you are using in virtualenv. It should be >=2.7.10 because it worked for me. Let us know if you still face this error.

Moreover, Thanks @deshraj !

**Comment by RishabhJain2018** [comment]
@isht3 We have fixed the bug in running development server. Please take a look at https://github.com/Cloud-CV/EvalAI/pull/1613. Also, make sure that you have the latest pull of master, once you start hacking.

**Comment by isht3** [comment]
@RishabhJain2018 YES! It started working. Thanks a lot!

**Pull request merged**
