### PR TITLE
Setup Sphinx Documentation 

### PR DESCRIPTION
**Pull request by AnshulBasia**
Let me know if there's any issue.

### CODE REVIEW

**Comment by AnshulBasia** [comment]
#854

**Comment by deshraj** [comment]
@AnshulBasia, sorry I didn't get time to review this. I will do it soon.

**Comment by deshraj** [comment]
@AnshulBasia something seems odd with the sphinx configiration. Also, there are bunch of features that we don't need for the documentation.

**Comment by AnshulBasia** [comment]
@deshraj  Can you brief me a little to what exactly needs to be fixed..? Thanks. I can retry if you suggest so, but I'll be doing the same thing again.

**Comment by deshraj** [comment]
Todos:
- [ ] Remove previous sphinx configuration files in `docs/`
- [ ] Setup new configuration with the following setting shown below:

This is the exact configuration that we want exactly. I tried to run on my system so that I can provide you the configuration that we want.

```shell
(env) DESHRAJs-MacBook-Pro:docs deshraj$ sphinx-quickstart
Welcome to the Sphinx 1.4.8 quickstart utility.

Please enter values for the following settings (just press Enter to
accept a default value, if one is given in brackets).

Enter the root path for documentation.
> Root path for the documentation [.]:

Error: an existing conf.py has been found in the selected root path.
sphinx-quickstart will not overwrite existing Sphinx projects.

> Please enter a new root path (or just Enter to exit):
(env) DESHRAJs-MacBook-Pro:docs deshraj$ sphinx-quickstart
Welcome to the Sphinx 1.4.8 quickstart utility.

Please enter values for the following settings (just press Enter to
accept a default value, if one is given in brackets).

Enter the root path for documentation.
> Root path for the documentation [.]:

You have two options for placing the build directory for Sphinx output.
Either, you use a directory "_build" within the root path, or you separate
"source" and "build" directories within the root path.
> Separate source and build directories (y/n) [n]:

Inside the root directory, two more directories will be created; "_templates"
for custom HTML templates and "_static" for custom stylesheets and other static
files. You can enter another prefix (such as ".") to replace the underscore.
> Name prefix for templates and static dir [_]:

The project name will occur in several places in the built documentation.
> Project name: EvalAI
> Author name(s): CloudCV Team

Sphinx has the notion of a "version" and a "release" for the
software. Each version can have multiple releases. For example, for
Python the version is something like 2.5 or 3.0, while the release is
something like 2.5.1 or 3.0a1.  If you don't need this dual structure,
just set both to the same value.
> Project version: 1.0
> Project release [1.0]:

If the documents are to be written in a language other than English,
you can select a language here by its language code. Sphinx will then
translate text that it generates into that language.

For a list of supported codes, see
http://sphinx-doc.org/config.html#confval-language.
> Project language [en]:

The file name suffix for source files. Commonly, this is either ".txt"
or ".rst".  Only files with this suffix are considered documents.
> Source file suffix [.rst]: .md

One document is special in that it is considered the top node of the
"contents tree", that is, it is the root of the hierarchical structure
of the documents. Normally, this is "index", but if your "index"
document is a custom template, you can also set this to another filename.
> Name of your master document (without suffix) [index]:

Sphinx can also add configuration for epub output:
> Do you want to use the epub builder (y/n) [n]:

Please indicate if you want to use one of the following Sphinx extensions:
> autodoc: automatically insert docstrings from modules (y/n) [n]:
> doctest: automatically test code snippets in doctest blocks (y/n) [n]:
> intersphinx: link between Sphinx documentation of different projects (y/n) [n]:
> todo: write "todo" entries that can be shown or hidden on build (y/n) [n]:
> coverage: checks for documentation coverage (y/n) [n]:
> imgmath: include math, rendered as PNG or SVG images (y/n) [n]:
> mathjax: include math, rendered in the browser by MathJax (y/n) [n]:
> ifconfig: conditional inclusion of content based on config values (y/n) [n]:
  viewcode: include links to the source code of documented Python objects (y/n) [n]:
n]: yhubpages: create .nojekyll file to publish the document on GitHub pages (y/n) [

A Makefile and a Windows command file can be generated for you so that you
only have to run e.g. `make html' instead of invoking sphinx-build
directly.
> Create Makefile? (y/n) [y]:
> Create Windows command file? (y/n) [y]:

Creating file ./conf.py.
Creating file ./index.md.
Creating file ./Makefile.
Creating file ./make.bat.

Finished: An initial directory structure has been created.

You should now populate your master file ./index.md and create other documentation
source files. Use the Makefile to build the docs, like so:
   make builder
where "builder" is one of the supported builders, e.g. html, latex or linkcheck.
```
- [ ] Convert `docs/contributions.rst` to markdown file
- [ ] Make sure that `README`, `docs/setup.md`, `docs/migrations.md`, `docs/contributions.md` and `docs/pull_request.md` in the toctree that will be created.

**Comment by deshraj** [comment]
@AnshulBasia please let me know if something is unclear. Would be happy to discuss more.

**Comment by deshraj** [comment]
@AnshulBasia please note that I have updated the configuration setup snippet that I have shared in above message.

**Comment by AnshulBasia** [comment]
@deshraj  Thanks a lot for detailed instructions.

**Comment by deshraj** [comment]
@AnshulBasia any update on this? Please let me know if you are busy with something else.

**Comment by AnshulBasia** [comment]
@deshraj please ignore this. I'll create a new pull request right away from scratch. I apologize for the delay, I got busy with other assignments. Thanks.

**Pull request closed without merging**
