### PR TITLE
collapsing at < 992 px 

### LINKED ISSUE #249: Sidebar on Dashboard view is not working properly for Mobile view.
Currently sidebar is collapsing at ~640px but it should be collapsed at screensize<992 px.

### PR DESCRIPTION
**Pull request by anweshknayak**
fixed #249 #250

### CODE REVIEW

**Comment by anweshknayak** [comment]
@aka-jain please review

**Comment by anweshknayak** [comment]
I need to fix header for other views too. I will fix it by tom.

**Comment by aka-jain** [comment]
@anweshnayak have you tested it for <992px?

**Comment by anweshknayak** [comment]
the dimensions like 640 x 960 doesn't work but the one  480 x 800 does work. for < 992.

**Comment by anweshknayak** [comment]
I have checked the corresponding variable values in the variable file. changed from 600 px  to 993 px.

**Comment by aka-jain** [comment]
<992 means it should also work for 991px.

So you have to write some customs CSS or you can take help from materialize CSS toggle menu section. 

Let me know if you can do that, otherwise we have to find some alternate way to do that :)

**Comment by anweshknayak** [comment]
I have tested with almost all the mobile views. it seems to work fine. As you said < 992. It means including the tablet views ?

**Comment by aka-jain** [comment]
Yup. For mobile it was already working.

**Comment by anweshknayak** [comment]
@aka-jain please review. Checked and tested on every view present in this chrome plugin ( https://chrome.google.com/webstore/detail/mobileresponsive-web-desi/elmekokodcohlommfikpmojheggnbelo ) . Working smooth for each and every view. Header is fixed and responsive. Let me know if anything more to do.

**Comment by anweshknayak** [comment]
@aka-jain delete a few lines of html which maybe were over-writing the settings for tablet and mobile view. Please review. and let me know if any changes required.

**Comment by anweshknayak** [comment]
and after these changes. after refreshing the page. the sidebar hides automatically ?

**Comment by aka-jain** [comment]
@anweshnayak: Thanks for your efforts, but I think it is creating problems, let me handle this.
Assigning this to myself :)

**Comment by aka-jain** [comment]
Also, will tell you about the changes that need to be made. Till then try other issues :)

**Comment by anweshknayak** [comment]
@aka-jain sure thanks :) 
shall I close this PR ?

**Comment by aka-jain** [comment]
Sure, I'm closing it.

**Pull request closed without merging**
