### PR TITLE
Create SETUP_PIPELINE_TO_PUSH_EVALAI_TO_DOCKER_REPOSITORY.md

### PR DESCRIPTION
**Pull request by nsjcorps**
I have added my suggestions to set up a pipeline to push EvalAI to Docker Repository.

Please review and let me know your comments.

https://github.com/nsjcorps/EvalAI/tree/spike-test is the link to the spike test

### CODE REVIEW

**Comment by nsjcorps** [comment]
@yashdusing @Ram81 @RishabhJain2018 @vkartik97 Please review

**Comment by nsjcorps** [comment]
I don't understand @vkartik97

**Comment by vkartik97** [comment]
Please share the branch or fork where you tried the approach mentioned in the doc/report.

**Comment by nsjcorps** [comment]
I made an edit now @vkartik97

**Comment by vkartik97** [comment]
I am not seeing changes in `.travis.yml` as proposed by you in doc, in the branch you referenced in PR description.

**Comment by nsjcorps** [comment]
The task was not to change it. it said outreach/research

**Comment by vkartik97** [comment]
The task also mentions that it's a spike:
> This task is just like a Spike. A spike(Software Engineering) is a short experiment to find out if a particular technique will work, or how complex it is going to be so that you can do a proper time estimate for the real thing.

**Comment by nsjcorps** [comment]
Should I attempt it? What will I fill im for the login details  @vkartik97

**Comment by nsjcorps** [comment]
I can do it. Just the details that I am wondering about

**Comment by vkartik97** [comment]
Yes! For login details, you can use your credentials. Make sure to hide it or else it will be echoed on Travis pipeline.

**Comment by nsjcorps** [comment]
How can I hide it? Would that not make not visible to everyone that views the file?

**Comment by vkartik97** [comment]
It's just a spike to test feasibility of the approach. If it's taking time and is complex, do let us know here.

**Comment by vkartik97** [comment]
Try using environment variables on Travis dashboard.

**Comment by nsjcorps** [comment]
Alright

**Comment by nsjcorps** [comment]
I did not see it om Travis dashboard

**Comment by nsjcorps** [comment]
I just saw it. Thanks!!

**Comment by nsjcorps** [comment]
I don't have a docker repo to push the image to. What should I do?

**Comment by vkartik97** [comment]
You can create your own on Docker Hub

**Comment by nsjcorps** [comment]
It won't let me create. it keeps redirecting me back to repositories

**Comment by nsjcorps** [comment]
I put a link to where I tested it. The build fails because I don't have access to your AWS, therefore the deploy script never gets called.

**Comment by nsjcorps** [comment]
@vkartik97

**Comment by nsjcorps** [comment]
However, it would work @vkartik97

**Comment by vkartik97** [comment]
Try adding this in travis environment variables:
```
AWS_SQS_QUEUE_NAME=evalai_submission_queue

AWS_ACCESS_KEY_ID=x

AWS_SECRET_ACCESS_KEY=x

AWS_ACCOUNT_ID=x

AWS_SQS_ENDPOINT=http://localhost:9324

PGPORT=5432

```

**Comment by nsjcorps** [comment]
ok

**Comment by nsjcorps** [comment]
@vkartik97 
It gets to the deployment part but it says I have tot tag the image. In order to tag the image, I have to run docker.
Which as mentioned earlier does not work on my PC
It logs in and gets to the point of pushing

**Comment by nsjcorps** [comment]
This docker part is really confusing
I don't know how to push it to repo

**Comment by nsjcorps** [comment]
I have been able to get it working
after 7 hours😢
It pushed successfully to all the docker repos
@vkartik97

**Comment by nsjcorps** [comment]
A link to the build https://travis-ci.org/nsjcorps/EvalAI/builds/631665682 .

**Comment by nsjcorps** [comment]
At least I learned something new😊😊...Docker!

**Comment by nsjcorps** [comment]
https://hub.docker.com/r/ndujay/evalai-staging-remote-worker/tags

https://hub.docker.com/r/ndujay/evalai-staging-frontend/tags

https://hub.docker.com/r/ndujay/evalai-staging-worker/tags

https://hub.docker.com/r/ndujay/evalai-staging-celery/tags

https://hub.docker.com/r/ndujay/evalai-staging-backend/tags

All links to repos.

@vkartik97 

I believe this is a very feasible solution

**Pull request closed without merging**
