### PR TITLE
Frontend: Changing route doesn't scroll to top in the new page

### PR DESCRIPTION
**Pull request by gauthamzz**
#744 is solved @spyshiv please review

### CODE REVIEW

**Comment by aka-jain** [comment]
@gauthamzz I think you took this issue in a wrong way. @spyshiv need your thoughts here.

**Comment by gauthamzz** [comment]
@aka-jain idk im confused , you just need to scroll back to top automatically when that page is loaded right ?

**Comment by aka-jain** [comment]
So do we have this directive already installed "smooth-scroll"?

**Comment by gauthamzz** [comment]
i saw that https://github.com/d-oliveros/ngSmoothScroll was already installed , so i used its functionality. I thought it might be easier. Should i change it ?

**Comment by anweshknayak** [comment]
Yeah in https://github.com/Cloud-CV/EvalAI/blob/master/bower.json#L26

**Comment by aka-jain** [comment]
@gauthamzz that's not a correct way to solve this. You have to make a function in run block of Angular so that every time the route changes the page scroll to it's topmost position. Smooth scroll is just a hack and if we go with it then we have to take care to add it in each views which might be a problem.

**Comment by aka-jain** [comment]
And that smooth scroll we used to scroll to a particular part of a page.

**Comment by aka-jain** [comment]
Fixed with #813

**Pull request closed without merging**
