### PR TITLE
Added long polling to leaderboard view

### PR DESCRIPTION
**Pull request by aka-jain**
@deshraj Please do regression testing for this.

### CODE REVIEW

**Comment by aka-jain** [comment]
@deshraj have a look please.

**Comment by deshraj** [comment]
screencapture-localhost-8888-web-challenges-challenge-page-1-my-submission-1486880132852

@aka-jain: this looks awesome. Can we change the color of the button from orange color to the color of the sidebar. I think then it would look nice. 

Also, another suggestion, can we have the text in the button in just one line? The two lines make it look odd.

**Comment by aka-jain** [comment]
@deshraj Purpose to use orange color is to highlight the update button, but if we go with the blue color then it will not be that much focused... getting?
Sure, will make it in single line;

**Comment by aka-jain** [comment]
screenshotatuploadcc_1486895698538
How about this one?

**Comment by deshraj** [comment]
@aka-jain this looks great. Did you get a chance to set the same for the leaderboard or do you want me to open an issue for that and can be referenced with this PR?

**Comment by aka-jain** [comment]
@deshraj I did same for leaderboard, have you checked that too?

**Comment by aka-jain** [comment]
@deshraj We can merge this, let's do leaderboard part in seperate issue.

**Comment by deshraj** [comment]
@aka-jain Sounds good to me. :-)

**Pull request merged**
