### PR TITLE
[WIP] Fixes #1602. Export challenge data in different formats

### LINKED ISSUE #1602: Export challenge data in different formats.
**Description:** Currently EvalAI supports exporting the submissions using csv only, but we want to extend this support to `json`, `xlsx`, `xls`, `yaml`, `html` .

### PR DESCRIPTION
**Pull request by yashdusing**
Fixes #1602. Added support for json, xlsx, html, yaml in my_submissions.

### CODE REVIEW

**Comment by yashdusing** [comment]
@RishabhJain2018 @deshraj could you please check for the PR ? All tests passed but the build still failed
screenshot-travis-ci org-2018 12 12-17-49-26

**Comment by gautamjajoo** [comment]
@yashdusing Hey! I could help you out with this. The travis is failing because of `flake8` error. Here's the screenshot:
flake8

**Comment by yashdusing** [comment]
> @yashdusing Hey! I could help you out with this. The travis is failing because of `flake8` error. Here's the screenshot:
> flake8

Thanks @gautamjajoo !

**Comment by yashdusing** [comment]
@RishabhJain2018 Could you please check if this is what is needed ?

**Comment by RishabhJain2018** [comment]
Thanks @yashdusing for the PR. I'll try to review it soon.

**Comment by yashdusing** [comment]
@RishabhJain2018 Made the respective changes

**Pull request closed without merging**
