### PR TITLE
[Frontendv2] Fixed Profile frontend

### PR DESCRIPTION
**Pull request by Alabhya268**
- [x] Removed profile `web container` to make it dynamic `web container` from base styling.

Before -
profile_before

After -
after
after 2

Now profile and footer of profile page use full width of the screen. 

@RishabhJain2018 @Ram81 , Please have a  look at this PR.

### CODE REVIEW

**Comment by Alabhya268** [comment]
@Ram81, ping for review.

**Comment by Alabhya268** [comment]
@Ram81

**Comment by Alabhya268** [comment]
@Ram81 , please give feedback on this PR.

**Comment by Alabhya268** [comment]
@Ram81, Please review this PR.

**Review by Ram81 — COMMENTED** [review]
@Alabhya268 I think we have discussed this in few of your old PRs related to dynamic containers. We follow the design of centering content when screen width increases and not scaling the container itself. This is design choice we have made. Please try https://eval.ai on multiple screen width for reference. Here;'s a screenshot of frontend v2 profile page with expected style 
Screen Shot 2021-04-07 at 7 10 52 PM

**Comment by Ram81** [comment]
Closing the PR as we don't use the following style for large screen width

**Comment by Ram81** [comment]
@Alabhya268 you can instead open a PR for centering content on larger screen if that doesn't work in frontend v2

**Pull request closed without merging**
