### PR TITLE
Fix #2694: django-import-export updated

### LINKED ISSUE #2694: django-import-export is not able to export the files
**Description:**
Django import-export isn't able to export the files. The list for the type of file to be exported doesn't open. Please see the screenshot for more reference.
Screenshot 2020-03-01 at 2 22 28 PM

### PR DESCRIPTION
**Pull request by Ayukha**
updates django-import-export tool (closes #2694 )

### CODE REVIEW

**Comment by Ayukha** [comment]
@RishabhJain2018 
screnshot

**Comment by RishabhJain2018** [comment]
@Ayukha Are you sure that this will work with `django==1.11.23`?

**Comment by RishabhJain2018** [comment]
The repository here says it requires django 2.0+ https://github.com/django-import-export/django-import-export

**Comment by Ayukha** [comment]
@RishabhJain2018 It is the master branch which is unreleased. I have used one of the versions from 1.x branch

**Comment by RishabhJain2018** [comment]
Thanks @Ayukha for fixing it quickly.

**Pull request merged**
