### PR TITLE
Made changes to project to make landing page responsive

### PR DESCRIPTION
**Pull request by S-ulphuric**

### CODE REVIEW

**Comment by deshraj** [comment]
@S-ulphuric can you please paste the screenshot here?

**Comment by S-ulphuric** [comment]
@deshraj Uploaded screenshots.
screenshot from 2017-12-11 14-07-04
screenshot from 2017-12-11 14-07-38
screenshot from 2017-12-11 14-08-14

**Comment by deshraj** [comment]
@S-ulphuric can you please complete the full task otherwise we would have to close the pull request?

**Comment by aka-jain** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
