### PR TITLE
[Frontendv2] Fixed cancel download and refresh button in Auth Token Card

### LINKED ISSUE #3276: Improvements in Auth Token Card
- [ ]   Cancel/Download not working
- [ ] Remove the Auth Token Label 
- [ ] Align copy to clipboard with the auth token
@Ram81 @RishabhJain2018 

Screenshot from 2021-03-02 23-12-55

### PR DESCRIPTION
**Pull request by Alabhya268**
This PR fixes #3276 .

- [x] Fixed ```Cancel``` button.
- [x] Fixed ```Download``` button.
- [x] Fixed ```Refresh Token``` button.

https://user-images.githubusercontent.com/57143358/109759012-6757e080-7c12-11eb-8d27-9ac8eb87e0dd.mp4

### CODE REVIEW

**Comment by Alabhya268** [comment]
@RishabhJain2018 @Ram81 , Please review this PR.

**Comment by Alabhya268** [comment]
@Ram81 , Ping for review.

**Comment by Ram81** [comment]
@Alabhya268 isn't this fixed already in [this ](https://github.com/Cloud-CV/EvalAI/commit/6e6bc811c194aab131128d1d15f845cc43ea90f2) commit ?

**Comment by Alabhya268** [comment]
@Ram81 ,I checked somehow it is working fine now but it was not working when issue #3276 was opened few days a go.
#3200 has been merged for quite a while now may be some other change affected it.

**Comment by Alabhya268** [comment]
I will close this PR after thoroughly verify if that the issue is fixed.

**Pull request closed without merging**
