### PR TITLE
added random file name function to images field

### LINKED ISSUE #1736: Change the uploaded challenge logo to some random name.
### Current Scenario:
Currently all the challenge logo images are being uploaded by the same name as the user has them on their local machine.

Hint: See the names for https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/models.py#L42 evaluation script.

### Deliverables:
We want that the logo images should be stored with unique random string on the server.

### PR DESCRIPTION
**Pull request by HargovindArora**
This PR fixes #1736 i.e. to generate random image name instead using the name of the image as uploaded by users. @RishabhJain2018 Please have a look at it!

### CODE REVIEW

**Comment by HargovindArora** [comment]
@RishabhJain2018 sure. I'll do it!

**Comment by HargovindArora** [comment]
@RishabhJain2018 
This is the image name:
screenshot from 2018-07-03 22-06-48

This is the changed name
screenshot from 2018-07-03 22-07-24

**Comment by RishabhJain2018** [comment]
@HargovindArora Looks good! Thanks for the fix :)

**Comment by deshraj** [comment]
@RishabhJain2018 @HargovindArora It looks like the migrations are missing from this file. Can you please add migrations file in another pull request?

**Comment by HargovindArora** [comment]
@deshraj Sure. I'll do it!

**Pull request merged**
