### PR TITLE
Add Editing for Challenge Using UI.

### LINKED ISSUE #1288: Add support editing a challenge details on UI
## Current Status

Currently, we have all the APIs required for editing the challenge. UI needs to be implemented so that the challenge hosts can edit the challenge on their own. 

## Deliverables

Note: There is a constraint that only challenge host should be able to edit the details on the frontend and hence the edit buttons should be avilable to the challenge hosts only.

1. Challenge host should be able to  edit the following fields:
- [x] Challenge name
- [x]  Challenge short description
- [x]  Challenge long description
- [x]  Terms and conditions
- [x]  submission guidelines
- [ ]  start date
- [ ]  end date
- [x]  evaluation script

2. For a challenge phase, following fields should be editable:
- [ ] phase name 
- [ ] phase description
- [ ] start date
- [ ] end date
- [ ] test_annotation file (Open a dialog box showing warning "Do you really want to do this? " Also, ask the host to enter the phase name here to make sure that he/she is not drunk while doing this)
- [ ] max submisasions per day
- [ ] max submissions

Note that this is a big issue and can be submitted as two different pull requests: one for editing the challenge details and the other for changing the challenge phase details. We want to add support for editing more meta details of the challenge and we would like to do that once we have these features in place.

### PR DESCRIPTION
**Pull request by RishabhJain2018**
Fix #1288 @deshraj @aka-jain @spyshiv Please review the PR.
**Dependency** : This PR is dependent on PR #1324 .

### CODE REVIEW

**Comment by aka-jain** [comment]
What left here @RishabhJain2018?
Please list all the sub features that you have added here.

**Comment by RishabhJain2018** [comment]
@aka-jain I have added the following features that can be edited by a challenge host:
- [x] Challenge name
- [x]  Challenge short description
- [x]  Challenge long description
- [x]  Terms and conditions
- [x]  submission guidelines
- [x]  evaluation script

@deshraj @aka-jain We can add the editing for ` challenge start date and challenge end date` in another PR as it would require the dependency of `datetime picker`. What are your thoughts about it ??

**Comment by aka-jain** [comment]
Sounds Good @RishabhJain2018.

Let me know once this PR ready for review

**Comment by RishabhJain2018** [comment]
@aka-jain Yes, this PR is ready for review. Please take a look!

**Comment by deshraj** [comment]
Doesn't seem to work properly on my system. @aka-jain @spyshiv can you please test it on your machine?

**Comment by RishabhJain2018** [comment]
@deshraj Can you please tell me the issues that you are facing ? Moreover, please install the `angular-trix` dependency for it to be working.

**Comment by deshraj** [comment]
Here are some of the changes:

```
- Challenge name edit dialog bix shows "Edit Terms and Conditions" instead of "Edit Challenge Name"
- Challenge name edit field should be an input field and not a text area
- Two way data binding for challenge phase editing is not there. 
- Add two way data binding for submission guidelines, terms and conditions
- `Update evaluation script` option should be in a different dialog box. Show a file button where you provide the link to the current evaluation script and then there host can choose to update the evaluation script there.
```

Rest all looks good to me. Sorry, earlier the npm installation was causing the problem.

**Comment by RishabhJain2018** [comment]
@deshraj I will add the two phase data binding in a new PR so as to make the code modular. :)

**Comment by RishabhJain2018** [comment]
@aka-jain @deshraj Please review the PR.

**Pull request merged**
