### PR TITLE
Add new partner organizations logos on homepage

### LINKED ISSUE #2286: Add new logos on homepage
Some of the new organizations have started using EvalAI for hosting their challenge, hence we would like to mention them as our users on the homepage -

Here are logos to be added alphabetically -
1. [UIUC](https://i.ibb.co/S3WnN7z/UIUC.png)
2. [NanKai University](https://upload.wikimedia.org/wikipedia/en/thumb/a/a5/Nankai_University_logo.svg/1200px-Nankai_University_logo.svg.png)
3. [MIT](https://iwi.mit.edu/sites/default/files/images/MIT_logo.png)
4. [IBM](http://pngimg.com/uploads/ibm/ibm_PNG19658.png)
5. [APTIV](https://www.aptiv.com/images/default-source/email-campaigns/aptiv_logo_color_rgb.png)
6. [Intel](https://github.com/cvwc2019/cvwc2019.github.io/blob/master/imgs/Intel_logo.png)
7. [UGM](https://banner2.kisspng.com/20190204/fjg/kisspng-gadjah-mada-university-ugm-logo-campus-5c591498b0cdc8.3184659715493418487242.jpg)
8. [Jinan University](https://english.jnu.edu.cn/_upload/site/00/5d/93/logo.png) (crop this image to contain only the logo)

### PR DESCRIPTION
**Pull request by Sanji515**
Fixes #2286 

#### Changes proposed in this pull request:

- Added new logos on homepage and fix the issue of not showing Facebook logo on small screen

- Here's the screenshots:

Screenshot from 2019-08-16 11-40-47
Screenshot from 2019-08-16 11-41-02

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
The `MIT` and `IBM` logo appears to be a little stretched and large. Please make it small.

**Comment by Sanji515** [comment]
@RishabhJain2018 Made the changes, please have a look.

**Comment by RishabhJain2018** [comment]
No, it still doesn't look good -
1. `Aptiv` logo is stretched vertically, it needs to be fixed.
2. `ebay` needs to be a little smaller.
3. `IBM` also needs to be a little smaller.
4. Please use `.png` in `Illinois` logo.
5. `IITM`, `JINAN university`, `Universitas Gajdah`  logo is stretched horizontally.
6. `MIT`, `SIOP` logo is stretched vertically

**Comment by deshraj** [comment]
@Sanji515 please share the final screenshot before this gets merged. :)

**Comment by Sanji515** [comment]
> @Sanji515 please share the final screenshot before this gets merged. :)

@deshraj Updated the PR description with the final screenshot, please have a look.

**Comment by deshraj** [comment]
Some of the logos seem squished to me. Can you please fix those?

**Comment by RishabhJain2018** [comment]
Closing this as https://github.com/Cloud-CV/EvalAI/pull/2455 is its extension.

**Pull request closed without merging**
