### PR TITLE
Docs: Fix verb in architecture_decisions

### PR DESCRIPTION
**Pull request by AliMirlou**

### CODE REVIEW

**Comment by Suryansh5545** [comment]
@AliMirlou Please Update the branch with master brand.

**Comment by RishabhJain2018** [comment]
@AliMirlou Can you please update the branch with master branch?

**Comment by AliMirlou** [comment]
@RishabhJain2018 Done.

**Comment by AliMirlou** [comment]
@RishabhJain2018 What happened?

**Pull request merged**
