### PR TITLE
Fix #1866: Update pagination size to 100 and add Submission ID

### LINKED ISSUE #1866: Update pagination size and add indexing
## Current Status
We have a pagination limit of 10 currently on the frontend for `My Submission` and `View All Submissions` Page. We would like to extend this limit to 100 submissions per page. Also, we should show the submission id as well as the first column

## Deliverables
- [ ] Update pagination on `My Submissions` Page to 100
- [ ] Update pagination on `View all submissions` Page to 100
- [ ] Add the column of `Submission ID` as the left most column for both `My Submission` and `View all submissions` page

### PR DESCRIPTION
**Pull request by yongzx**
#1866 
### Deliverables
- [X] Update pagination on My Submissions Page to 100
- [X] Update pagination on View all submissions Page to 100
- [X] Add the column of `Submission ID` as the left most column for both `My Submission` and `View all submissions` page.
view all submissions

my submissions

### CODE REVIEW

**Comment by vkartik97** [comment]
Hi @yongzx  
If Travis CI is not passing only because of `test_get_remaining_submission_when_submission_made_three_days_back`, then no need to worry!
[EvalAI/pull#2063](https://github.com/Cloud-CV/EvalAI/pull/2063) deals with this issue.
Please let me know if you have questions. :)

**Comment by yongzx** [comment]
Overall,
* [x] Update pagination on My Submissions Page to 100
* [x] Update pagination on View all submissions Page to 100
* [x] Add the column of `Submission ID` as the left most column for both `My Submission` and `View all submissions` page. 
* [x] Fix and add unit tests for `encode_data` and `decode_data` 

Fixes: #1866 #2107 

@RishabhJain2018 @deshraj May I know what else should I add? Thanks!

**Comment by gautamjajoo** [comment]
@yongzx Can you remove the code added for pagination size as https://github.com/Cloud-CV/EvalAI/pull/2198 has already been merged!

**Comment by RishabhJain2018** [comment]
Hey, @yongzx Thanks for the PR. I've already added the feature for it and also I think Submission-ID will confuse the user with Submission No. Please let me know about your thoughts.

**Comment by RishabhJain2018** [comment]
Hence, I'm closing it temporarily. Please do pick up any other issue.

**Pull request closed without merging**
