### PR TITLE
Fix #1364 Updated color scheme for pop up notifications

### LINKED ISSUE #1364: Try and suggest different color schemes for pop up info notifications
**Description:** The color scheme must be in accordance with our new UI. Student should try different colours with notification toast so as to match the UI.

### PR DESCRIPTION
**Pull request by gautamjajoo**
Fixed #1364 and updated version of #1419. 
@aka-jain @RishabhJain2018

### CODE REVIEW

**Comment by aka-jain** [comment]
@gautamjajoo can you please attach the screenshot of all popups here?

**Comment by gautamjajoo** [comment]
@aka-jain how can I send screenshots of different colours. Like for the error display(red), I can send when the user tries to upload a wrong zip file for creating a challenge.

**Comment by RishabhJain2018** [comment]
@gautamjajoo For success screenshot you can capture after registering yourself, for info you can capture after logging out. Please feel free to ask if you have further doubts.

**Comment by spyshiv** [comment]
@aka-jain It's your call. Please review this PR. If we can go with selected colors then merge this ASAP.

**Pull request merged**
