### PR TITLE
Made hosts team-name unique

### PR DESCRIPTION
**Pull request by Rishav09**

### CODE REVIEW

**Comment by deshraj** [comment]
@Rishav09 can you check why the travis build is failing?

**Comment by deshraj** [comment]
@Rishav09 Please let me know if you have issues in solving this issue. I would like to fix it then since we need this feature ASAP.

**Comment by Rishav09** [comment]
@deshraj fixed them,now you can merge them,earlier I missed some mighty blankspace.

**Comment by deshraj** [comment]
@Rishav09 can you please make changes same as what I asked in #524

**Comment by deshraj** [comment]
Closing this since already taken care of in #544. Thanks for your help @Rishav09 :-)

**Pull request closed without merging**
