### PR TITLE
Front-end Unit Tests: Challenge controller

### PR DESCRIPTION
**Pull request by Sanji515**
PR contains the front-end tests of the `Challenge Controller`

### CODE REVIEW

**Comment by Sanji515** [comment]
@RishabhJain2018 @galipremsagar Please review

**Comment by galipremsagar** [comment]
@Sanji515 , did you introduce Changes to Challenge controller on purpose ? Asking this to confirm if it was introduced due to some reason?

**Comment by Sanji515** [comment]
> Update: looks like you did refactoring?

yes, because if some functions are defined below the call so in unit tests it is giving me error that it is not defined to that call

Apart from that did you change anything?

no, only initialized one thing `vm.team= {}`

**Comment by Sanji515** [comment]
@galipremsagar I've resolved the above errors, please review

**Comment by RishabhJain2018** [comment]
@Sanji515 Please resolve the conflicts here.

**Pull request merged**
