### PR TITLE
Deleted unnecessary folders

### LINKED ISSUE #1165: Remove unnecessary files from examples folder.
Remove the folder `test_zip_file` and `test_zip_file.zip` from the `EvalAI/examples/example1` folder.

### PR DESCRIPTION
**Pull request by HargovindArora**
Fix #1165. Remove Unnecessary folders from examples folder.

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@HargovindArora Can You please fix the failing test cases.

**Comment by the-dagger** [comment]
@RishabhJain2018 I believe that the folders are used for unit testing and hence deleting them results in failing travis check.

**Comment by RishabhJain2018** [comment]
@the-dagger yes, you are right. :+1: I forgot this earlier but now I remember :smile:
So, we can't remove these folders . 
@HargovindArora Thanks for the help. :)

**Comment by HargovindArora** [comment]
@RishabhJain2018 Ohh. Okay.

**Pull request closed without merging**
