### PR TITLE
Made participants team name unique

### PR DESCRIPTION
**Pull request by Rishav09**

### CODE REVIEW

**Comment by deshraj** [comment]
@Rishav09 can you check why the travis build is failing?

**Comment by deshraj** [comment]
@Rishav09 it would be great if you can write tests for this model in the sam pull request so as to make sure that it is working properly?

**Comment by deshraj** [comment]
Also, I would like you to push the migrations with name for the same.

**Comment by Rishav09** [comment]
@deshraj  I am just figuring out how to write tests.I think,I may need some help for this.

**Comment by deshraj** [comment]
@Rishav09 you can take help from here https://github.com/Cloud-CV/EvalAI/blob/master/tests/unit/challenges/test_models.py

**Comment by RishabhJain2018** [comment]
@Rishav09 I can help you with the tests.

**Comment by deshraj** [comment]
@Rishav09 sorry, I have to close this PR since I have already implemented this feature and moreover we needed it ASAP. :-)

**Pull request closed without merging**
