### PR TITLE
django cache backend for the development environment.

### PR DESCRIPTION
**Pull request by RishabhJain2018**
#363 solved. @deshraj Please review the PR.

### CODE REVIEW

**Comment by deshraj** [comment]
I think you would want to move `python-memcached==1.58` to `requirements/prod.txt`

**Comment by RishabhJain2018** [comment]
@deshraj One more I would like to suggest that, can we also integrate **django-debug-toolbar** for better development ?

**Comment by deshraj** [comment]
Sounds like a good idea but we might want to have a look at other packages as well before moving on with this one.

**Comment by RishabhJain2018** [comment]
@deshraj Please help in resolving travis checks.

**Comment by deshraj** [comment]
@RishabhJain2018 try solving this https://travis-ci.org/Cloud-CV/EvalAI/builds/189869889#L1079

This will fix the issue

**Comment by RishabhJain2018** [comment]
@deshraj Please review the PR.

**Pull request merged**
