### PR TITLE
Worker: Refactor and add tests download_and_extract_zip_file

### PR DESCRIPTION
**Pull request by nikochiko**
Changes proposed:
* Refactor some part of function `download_and_extract_zip_file` into two functions `extract_zip_file` and `delete_zip_file`. 
* This way, any updates in the future in the extracting / deleting mechanisms can be made without editing the tests which will be independent of the package used.
* Makes it easier to debug

### CODE REVIEW

**Comment by yashdusing** [comment]
@nikochiko could you please check for the coverage ?

**Comment by nikochiko** [comment]
@yashdusing The coverage issue has been fixed :+1:. Please have a look.

**Comment by pushkalkatara** [comment]
LGTM +1

**Comment by yashdusing** [comment]
LGTM 👍

**Comment by nikochiko** [comment]
@Ram81 @RishabhJain2018 I have merged the changes into one PR! 

Please let me know when you create the new task. :+1:

**Comment by nikochiko** [comment]
@Ram81 I have claimed and submitted this task for review: https://codein.withgoogle.com/dashboard/task-instances/5393905223204864/ 

*P.S. Sorry for the extra trouble due to new changes

**Comment by yashdusing** [comment]
LGTM 👍

**Pull request merged**
