### PR TITLE
Backend Error Messages: Submission Error Backend Messages Shown.

### PR DESCRIPTION
**Pull request by RishabhJain2018**
#511 solved. @deshraj @aka-jain @spyshiv Please review the PR.

### CODE REVIEW

**Comment by aka-jain** [comment]
@RishabhJain2018 I think this has to be done on backside to submission API not on frontend side.
@deshraj Am I right? It would be good if you give a brief here.

**Comment by deshraj** [comment]
@aka-jain So the issue was to show the error messages thrown from the backend instead of showing the hard coded message on frontend if some error occurs during the submission.

**Comment by RishabhJain2018** [comment]
@deshraj @aka-jain The error was to access the dictionary's item which is coming in response to frontend from backend. So, we can do both ways either change the `key` in the api in backend or change the response object's `key` in frontend. So, what should we do ?

**Comment by aka-jain** [comment]
@RishabhJain2018 , Wait I'm working on your PR.

**Comment by aka-jain** [comment]
@RishabhJain2018 : I've to close this PR. Have to do major changes here. Thanks for the efforts :)

**Comment by RishabhJain2018** [comment]
@aka-jain No problem. :-)

**Pull request closed without merging**
