### PR TITLE
[Frontend_v2]Improvements in UI

### PR DESCRIPTION
**Pull request by Kajol-Kumari**
- User will not be able to see the login page if already logged in, instead a message will be show to them.

- Padding fixes

- Teams search box shifting fixed

- Removed notification of `Please select a host team` instead the instruction will be shown in the host team list title.

- Phase detail UI improved

- Navigate to `my submissions` tab after successful submission.

- Clear error and data on phase change in submission form.

- Card alignment bug Fix

- Privacy-policy page Fixed

Previous UI:
before

Phase detail page UI now:
imageedit_4_9726294551

When user tries to log In again even when they have already logged In:
imageedit_2_9364657780

Privacy-policy Page GIF:
privacy-policy

\cc: @RishabhJain2018 @deshraj @Sanji515 @Shekharrajak @lunayach

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@Ram81 Can you please test this on your local?

**Comment by Ram81** [comment]
@Kajol-Kumari the terms and conditions card is still misaligned
Screen Shot 2020-08-17 at 8 57 55 PM

Also in the submit page when I enter more than 1 characters in the URL field the error text `Enter a valid URL` goes away. Is this expected?

And the box shadow of `Teams search box` has a blueish color. Is this the expected color?

**Comment by Kajol-Kumari** [comment]
@Ram81 Can you please check now, if everything is working fine or not?

**Comment by Ram81** [comment]
@Kajol-Kumari everything else works fine. Just the search box is not being highlighted. @RishabhJain2018 @deshraj do we want the team name search box to highlight when focused?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari everything else works fine. Just the search box is not being highlighted. Sorry if I wasn't clear when I mentioned the search box looks blueish. I didn't mean that we should remove it, I just asked was the box shadow color appropriate or do we have to change it to some other shade. @RishabhJain2018 @deshraj do we want the team name search box to highlight when focused?

Hey @Ram81 so earlier I had added a highlight when focused but it was causing a bit of shifting which is one of the issue listed in the doc and that is the reason I removed the highlight part.

\cc: @RishabhJain2018 @deshraj

**Review by Ram81 — APPROVED** [review]

**Comment by RishabhJain2018** [comment]
> @RishabhJain2018 @deshraj do we want the team name search box to highlight when focused?

Not sure if I'm getting this correct but we will check it when it is deployed on staging.

**Pull request merged**
