### PR TITLE
Fix #2625 Updated the Arxiv link to the SOSP 2019 Paper link

### LINKED ISSUE #2625: Update paper link on landing page and README
Currently the paper link in README and the landing page points to the arxiv version. Recently, the paper was accepted at AI Systems Workshop at SOSP 2019. We want to update the link and bibtext to that. 

Here is the updated link: http://learningsys.org/sosp19/assets/papers/23_CameraReadySubmission_EvalAI_SOSP_2019%20(8)%20(1).pdf

### PR DESCRIPTION
**Pull request by bosecodes**
Changed the link to the paper from the Arxiv website to the one mentioned in SOSP 2019 as per #2625

### CODE REVIEW

**Comment by bosecodes** [comment]
Please see to it @Suryansh5545

**Comment by Suryansh5545** [comment]
@bosecodes LGTM:+1:

**Comment by Sanji515** [comment]
@bosecodes Can you please resolve the conflicts here?

**Comment by bosecodes** [comment]
Done. I really await the final review now.

**Comment by bosecodes** [comment]
Oops, yeah I've updated with the changes you suggested :)

**Pull request merged**
