### PR TITLE
Fix #3377 not send email to anonymous users

### LINKED ISSUE #3377: Show successful notification only when the user is registered and resets the password
### Observed Behaviour
Currently, if a user has forgotten his password he can enter the email address and a password reset link will be shared. 
Even if the email address is not registered a successful notification is popped up.

### Expected Behaviour
Password reset should only be sent when the user is registered. Otherwise, display an error.

@Ram81 @RishabhJain2018

### PR DESCRIPTION
**Pull request by Happytocode24**
IMPORTANT NOTES (please read, then delete):

* The PR title should start with "Fix #bugnum: " (if applicable), followed by a clear one-line present-tense summary of the changes introduced in the PR. For example: "Fix #bugnum: Introduce the first version of the collection editor.".

* Please make sure to mention "#bugnum" somewhere in the description of the PR. This enables GitHub to link the PR to the corresponding bug.

Please also make sure to follow the [style rules](https://github.com/Cloud-CV/EvalAI/blob/master/.github/CONTRIBUTING.md#style-rules).

### CODE REVIEW

**Comment by Ram81** [comment]
@Happytocode24 please stop creating multiple PRs with same changes.

**Comment by Happytocode24** [comment]
I am unable to pull request from my machine I don’t know why

**Comment by Ram81** [comment]
@Happytocode24 please test these changes on your local repo. Not the Org. project repository.

**Comment by Happytocode24** [comment]
Can you tell me , how to delet these multiple PR’s ? Sorr for mess

**Pull request closed without merging**
