### PR TITLE
Fix #1957 Add tests for get_broker_urls API

### LINKED ISSUE #1957: Add tests for get_broker_urls API
We have added a new API in [apps/challenges/view.py](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L1330). Hence, tests are required in order to make the system robust.

Please feel free to ask if there are more questions/doubts. I'll be happy to help.

### PR DESCRIPTION
**Pull request by inishchith**
Added tests for `get_broker_urls` API.
I've added 2 tests
- `test_get_broker_urls_when_user_is_not_superuser`: when the request is made by a user who is not a super user hence [tesing](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L1335).
- `test_get_broker_urls_when_challenge_is_approved`: when the request is made by a superuser hence [testing](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L1338), when challenges are approved.

The reason why i've added superuser to `BaseAPITestClass` is the convenience of adding further tests related to superuser.

@RishabhJain2018 Please do let me know if any changes required .

Closes #1957

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
No, this looks good as ideally there should only be two test cases and you are covering them.

**Comment by inishchith** [comment]
@RishabhJain2018 The failed tests are due to mismatch in response format 🙈 which #1970 fixes.

**Comment by inishchith** [comment]
@RishabhJain2018 Please review and do let me know if any changes required .

**Comment by RishabhJain2018** [comment]
Thanks for the reminder @inishchith. I'll do it by tomorrow.

**Comment by RishabhJain2018** [comment]
Hi @inishchith , We might change the format of this API, so I am keeping it on hold for now but will surely merge it.
Please feel free to take up any other issue.

**Comment by RishabhJain2018** [comment]
@inishchith Please resolve the conflicts. Let's get this merged 🎉

**Comment by inishchith** [comment]
@RishabhJain2018 I had updated the PR, can you have a look again?

Thanks!

**Pull request closed without merging**
