### PR TITLE
input field cleared

### PR DESCRIPTION
**Pull request by parismita**
issue #424

### CODE REVIEW

**Comment by aka-jain** [comment]
@parismita : great efforts, but have to do some changes here. Actually we are using view modal (vm) instead of $scope so please use the same. You can take help from other parts in same the controller. 
Also there is no need to add a click function on submit button, just add reset functionality on success of Create team.
I hope you got my points, let me know if have any problem :)

**Comment by parismita** [comment]
yeah...click function removed ....rest i m doing

**Comment by parismita** [comment]
@aka-jain changed and its working on my pc ...please check it

**Comment by spyshiv** [comment]
@parismita: Since 4 commits you've done are related to single module so you should squash these commits into one. 
Guidline:[How to squash commits](http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) 
Let me know if you face any issue.

**Comment by deshraj** [comment]
@spyshiv I think we are good to go with unsquashed commit since we have set `merge with squash` in github. @spyshiv Let me know if this looks good so that I can merge it.

**Comment by aka-jain** [comment]
@parismita : Looks good :)
@deshraj : Merge this please.

**Pull request merged**
