### PR TITLE
Add validation to show message on Challenge Analysis page

### PR DESCRIPTION
**Pull request by NSDCars5**
Google Code-In submission for task "[EvalAI] Add validation on create challenge page."

### CODE REVIEW

**Comment by deshraj** [comment]
@NSDCars5 I think you made changes in the wrong file for that task. Please make changes in the correct file and create another pull request. Closing this one.

**Comment by NSDCars5** [comment]
@deshraj Isn't this the required behavior? I got this after making the above change:

screenshot_2017-12-09_12-35-28

**Comment by NSDCars5** [comment]
@deshraj Hey, could you confirm this once? The GCI task actually linked to this page: https://codein.withgoogle.com/dashboard/task-instances/4721214897520640/

**Comment by deshraj** [comment]
Sorry for the misunderstanding. It happened due to the ambiguous title of the pull request. Can you please create the same pull request again? I cannot reopen this since you have deleted the repository from which the pull request was created.

**Pull request closed without merging**
