### PR TITLE
Fix: Test case runtime warnings

### PR DESCRIPTION
**Pull request by Ram81**

### CODE REVIEW

**Comment by Ram81** [comment]
@RishabhJain2018 @deshraj to fix those warnings I have to make `auto_now_add=False`, but can we allow submitted_at=null ?

**Comment by RishabhJain2018** [comment]
I am not in favour of making `auto_now_add=False` and the other change too.
@Ram81 Can you please try this solution https://stackoverflow.com/a/45080605?

**Comment by Ram81** [comment]
@RishabhJain2018 I tried all three, none of them worked. Issue seems to be with `auto_now_add=True`

**Comment by RishabhJain2018** [comment]
Closing this now since #1987 fixes the same thing.

**Pull request closed without merging**
