### PR TITLE
Fix: Sticky footer added for join-us page(#824)

### PR DESCRIPTION
**Pull request by Ram81**
@aka-jain @deshraj please review!

### CODE REVIEW

**Comment by Ram81** [comment]
@aka-jain we need to apply this sticky footer to all the other pages also as we've used sticky footer previously only for dashboard view.

**Comment by Ram81** [comment]
footer
snapshot of the page

**Comment by aka-jain** [comment]
Classes are already present for sticky footer. Please take reference from landing page. And do changes accordingly.

**Comment by Ram81** [comment]
@aka-jain changes done Please review!

**Comment by Ram81** [comment]
abc
Snapshot

**Pull request merged**
