### PR TITLE
Fix #2137 Added SIOP logo to landing page

### LINKED ISSUE #2137: Add SIOP logo in "Who uses EvalAI" list.
Here is the SIOP [logo](https://drive.google.com/file/d/1zcw3uqDyM1iHha-o1_zUzKSAkt__98sG/view)

### PR DESCRIPTION
**Pull request by yashbhutoria**
Closed #2157 and made this new PR

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
Thanks @yashbhutoria for the PR. Can you please also add the screenshot of it.

**Comment by yashbhutoria** [comment]
Here it is
Screenshot from 2019-03-18 12-23-42

**Comment by gautamjajoo** [comment]
@yashbhutoria Could you add the organizations in alphabetical order and please paste the screenshot of the screen in mobile view as well.

**Comment by yashbhutoria** [comment]
Screenshot from 2019-03-19 15-51-04
Screenshot from 2019-03-19 15-51-17

**Comment by RishabhJain2018** [comment]
@yashbhutoria The logo height is a little more than the existing ones. Can you make it align with the existing ones. You might want to fix the width too.

**Comment by yashbhutoria** [comment]
Screenshot from 2019-03-22 12-11-18
Screenshot from 2019-03-22 12-11-37

**Comment by RishabhJain2018** [comment]
@yashbhutoria This looks good! Thanks for the fix!

**Pull request merged**
