### PR TITLE
#2291 OAuth Integration (Github)

### PR DESCRIPTION
**Pull request by rohitjha941**
> What is Added
- OAuth (github) using Django Allauth & Django RestAuth 

>Testing Steps
- Create an OAuth APP on Github, Redirect URL should be `<frontend-url>/auth/oauth-redirect/github/`.
- Set the FrontEnd URL in the environment variable FRONTEND_URL.
- Change client id in frontend (login page)  
- Follow Django AllAuth Documentation to add a site 

>What is left?
- I need to set client id for frontend in  env, I am unable to find where env files of the frontend are stored

I made some mistake while merging( #2353) with master so creating new MR, I have Incorporated all changes requested

### CODE REVIEW

**Comment by rohitjha941** [comment]
58772756-ef412e80-85d7-11e9-8477-0ce772f8822f

**Comment by RishabhJain2018** [comment]
Thanks, @rohitjha941 for the PR. Can you please resolve the conflicts here?

**Comment by RishabhJain2018** [comment]
Also, @Sanji515 Can you please review it once the conflicts are resolved.

**Comment by rohitjha941** [comment]
@RishabhJain2018 Resolved Conflicts,

**Comment by rohitjha941** [comment]
@RishabhJain2018 Can you please close #2353

**Comment by rohitjha941** [comment]
@RishabhJain2018  Can you please have a look

**Comment by rohitjha941** [comment]
@RishabhJain2018 @Sanji515 Can you please review this. 
Thanks

**Pull request closed without merging**
