### PR TITLE
Fixes #1669 - Add new logo in home page

### LINKED ISSUE #1669: Add new logo in home page
### Deliverables
Add Draper logo in the home page
Logo: http://www.draper.com/sites/all/themes/draper/img/Draper-Primary-Logo-RGB.png

### PR DESCRIPTION
**Pull request by gautamjajoo**
Fixes #1669 - Add new logo in home page.
@deshraj @RishabhJain2018

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@gautamjajoo Can you please paste the screenshot ?

**Comment by gautamjajoo** [comment]
cloudcv

**Comment by deshraj** [comment]
@gautamjajoo the logo seems to be vertically stretched. Please fix it.

**Comment by RishabhJain2018** [comment]
Ohh..I didn't check the original logo. Yes, you are right.

**Comment by RishabhJain2018** [comment]
@gautamjajoo Any update on this?

**Comment by gautamjajoo** [comment]
@RishabhJain2018 Just updating!

**Comment by RishabhJain2018** [comment]
@gautamjajoo Can you please paste the screenshot ?

**Comment by gautamjajoo** [comment]
draper

When I add the original picture, the webpage is like the above.

**Comment by gautamjajoo** [comment]
@RishabhJain2018 The previous one was good, I think so.

**Comment by RishabhJain2018** [comment]
@gautamjajoo Please take a look at PR #1679 . This will help you understand how you can use `id` to modify a particular item. Thanks for your efforts! :-)

**Comment by gautamjajoo** [comment]
Closing this with respect to #1679 .

**Pull request closed without merging**
