### PR TITLE
Updated the Team Page 

### LINKED ISSUE #3130: Fix About us page css inconsistencies in frontend v2
### Description

Fix the about us page on large screens. Currently, the about us page css is not consistent between frontend v1 and v2. The page css is broken for larger screens in frontend v2. Page css should be same as frontend v1

Frontend V1:
Screen Shot 2021-01-10 at 7 30 04 PM

Frontend V2
Screen Shot 2021-01-10 at 7 30 06 PM

 Also, make sure that the content css is the same as that of the frontend V1.

### PR DESCRIPTION
**Pull request by gautamjajoo**
Updated the team page and also solved the css inconsistencies of all the other pages for large screen.
Fixes #3130 #3131 

screencapture-0-0-0-0-4200-our-team-2021-01-11-14_39_15

@RishabhJain2018 @Ram81

### CODE REVIEW

**Comment by Ram81** [comment]
@gautamjajoo can you also share a screenshot for the zoomed-out page?

**Comment by gautamjajoo** [comment]
@Ram81 I didn't understand zoomed-out page?

**Comment by Ram81** [comment]
@gautamjajoo I meant to take a screenshot by reducing the zoom setting of your browser to < 100%. This will show us how the webpage will look for bigger screens. As one part of the task was to fix css for larger screens for Our team page.

**Comment by gautamjajoo** [comment]
This is for 80%

screencapture-0-0-0-0-4200-our-team-2021-01-11-18_44_31

**Comment by Ram81** [comment]
@gautamjajoo If you look at https://eval.ai/team you'll see the team member cards are centered at 50% zoom. We have to make css behavior same for both frontend v1 and v2 Our team page. Can you please make the required changes.

Here's the screenshot of 50% zoom:

Screen Shot 2021-01-11 at 6 48 01 PM

**Comment by gautamjajoo** [comment]
Fixed it for team page, will update for about-us page in a new PR.

Screenshot of 50% zoom.

Screenshot from 2021-01-12 01-14-24

**Review by Ram81 — APPROVED** [review]
LGTM 👍

**Comment by gautamjajoo** [comment]
@Ram81 @RishabhJain2018 Please don't merge the PR, the about us page is not working responsively after the new commit.

**Comment by RishabhJain2018** [comment]
@gautamjajoo Please let me know when you want us to review and merge this PR.

**Comment by gautamjajoo** [comment]
@RishabhJain2018 This PR can be merged for the Team Page. I will open a new PR with the changes regarding the about-us page.

**Comment by gautamjajoo** [comment]
@RishabhJain2018 The PR is done with fixes of both about-us and team page.

**Comment by RishabhJain2018** [comment]
@gautamjajoo Can you please paste the screenshot for the About Us Page.

**Comment by gautamjajoo** [comment]
Normal:
screencapture-0-0-0-0-4200-about-2021-01-17-00_04_24

50% zoom:
screencapture-0-0-0-0-4200-about-2021-01-17-00_05_38

**Pull request merged**
