### PR TITLE
Frontend: Improves password change feature view

### LINKED ISSUE #810: Improved password change feature view.
Steps to do:
1. After successfully password change, show a modal which will asks user to "stay" or "login again".
2. If user selects "Stay" then do nothing if user clicks "Login again" then make user log out and open login page view.

@spyshiv any thoughts?

### PR DESCRIPTION
**Pull request by mayank-agarwal-96**
This is a pull request to fix #810. @aka-jain Please check and suggest changes.

### CODE REVIEW

**Comment by mayank-agarwal-96** [comment]
@deshraj @aka-jain Please review.

**Comment by aka-jain** [comment]
@mayank-agarwal-96 we are already using default modal of angular material. So please take reference from invite team member section. There is no need to integrate seperate modal for this.

**Comment by mayank-agarwal-96** [comment]
@aka-jain Sorry, I didn't notice that. I'll update the PR accordingly.

**Comment by mayank-agarwal-96** [comment]
@aka-jain I have reverted the changes and now used angular material modal for this. Please check.

**Comment by mayank-agarwal-96** [comment]
@aka-jain Please check the PR.

**Comment by deshraj** [comment]
Closing it since we would want to control this at the backend side and not at the client side.

**Pull request closed without merging**
