### PR TITLE
Use allowed submission type field from backend

### PR DESCRIPTION
**Pull request by Ram81**
### Description

This PR adds changes to use `allowed_submission_types` field value for file upload restriction on submit page. EvalAI-Starters [PR](https://github.com/Cloud-CV/EvalAI-Starters/pull/30)

### CODE REVIEW

**Review by RishabhJain2018 — APPROVED** [review]

**Review by RishabhJain2018 — CHANGES_REQUESTED** [review]
@Ram81 Can you please add the corresponding change in challenge create API.

**Comment by RishabhJain2018** [comment]
@Ram81 We also missed the change in uploading files through URLs. Can you please add that as well.

**Comment by Ram81** [comment]
>@Ram81 Can you please add the corresponding change in challenge create API.

Please see the serializer changes this is already done.

>@Ram81 We also missed the change in uploading files through URLs. Can you please add that as well.

Done

**Comment by RishabhJain2018** [comment]
>Please see the serializer changes this is already done.

Do we not need to parse the values from the challenge YAML in the challenge creation API or am I missing something here?

**Comment by Ram81** [comment]
>Do we not need to parse the values from the challenge YAML in the challenge creation API or am I missing something here?

Once you expose the field in the `ChallengePhaseCreateSerializer` it will initialize the serializer values from yaml data.

**Review by RishabhJain2018 — APPROVED** [review]

**Pull request merged**
