### PR TITLE
Fix #1458 and #1080: Display error if team is not selected and add functionality to disable challenge

### LINKED ISSUE #1458: No error is shown if a team is not selected.
A red bar is visible on the top right corner when trying participate in a challenge without any team selected.

screenshot from 2018-01-10 21-31-38

I would like to take this issue.

### PR DESCRIPTION
**Pull request by codervivek**
response.data returns a HTML string which doesn't have data or detail keys.
Please suggest if I have to add other error cases.

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
Hi @codervivek , Can you please open an issue with the screenshot when the error is not displayed(Host Team or participant Team)?

**Comment by codervivek** [comment]
I have already done that. Please check #1458 .

**Comment by RishabhJain2018** [comment]
Ohh..my bad!

**Comment by codervivek** [comment]
I have also added the code to disable challenge for issue #1080 .

**Comment by RishabhJain2018** [comment]
Hey @codervivek Can you please open two different PR's for the two issues #1458 and #1080 . Actually, we accept one PR for one issue only. Please let me know when you are done. I will review them and get them merged asap.

**Comment by codervivek** [comment]
@RishabhJain2018 I have made the PRs but there seems to be some error for same code. Could you please tell me where the problem is?

**Comment by RishabhJain2018** [comment]
@codervivek I am closing this PR as you have already opened two different Pull Requests. :-)

**Pull request closed without merging**
