### PR TITLE
Contact Us: New App Contact Us deleted.

### PR DESCRIPTION
**Pull request by RishabhJain2018**
#562 Solved. @deshraj @TroJan Please review the PR.

### CODE REVIEW

**Comment by deshraj** [comment]
@RishabhJain2018 I think you misunderstood the issue. We don't want to create a separate app for ContactUs. Please use the `web` app for that.

**Comment by RishabhJain2018** [comment]
@deshraj ohh.my bad . So do I also need to move [these](https://github.com/Cloud-CV/EvalAI/commit/a79d01a3a49cc0ce389973ef44a2202522e5ddd1) `models` to `web app`. I thought as the models were created in a different app in this [commit](https://github.com/Cloud-CV/EvalAI/commit/a79d01a3a49cc0ce389973ef44a2202522e5ddd1), so we are using a new app.

**Comment by deshraj** [comment]
Yeah, please remove that as a different PR and add the changes in the `web` app

**Comment by RishabhJain2018** [comment]
yeah sure.

**Pull request merged**
