### PR TITLE
Add note about default resources in the manage page

### PR DESCRIPTION
**Pull request by gchhablani**
This commit adds the message needed to inform the users that by default
certain resources are provided and if they need additional resources
they should contact the admin.

### CODE REVIEW

**Review by Ram81 — CHANGES_REQUESTED** [review]
@gchhablani can you post a screenshot of the UI with these changes, You can just post a screenshot of the Manage tab

**Comment by gchhablani** [comment]
@Ram81 This is from `frontend`. Not sure how to verify from `frontend_v2`. Can you please help me with that?
image

**Comment by gchhablani** [comment]
For both frontends:
`frontend`:
image
`frontend_v2`:
image

**Comment by Ram81** [comment]
In frontend v2 as well can you put the new card at the same position as frontend v1.

**Comment by gchhablani** [comment]
image

**Review by Ram81 — APPROVED** [review]

**Pull request merged**
