### PR TITLE
Add tests for dramatiq worker

### PR DESCRIPTION
**Pull request by nikochiko**
Changes proposed in pull request:
* Add unit tests for dramatiq worker proposed in #2593

### CODE REVIEW

**Comment by nikochiko** [comment]
Done! Ready for review now!
I will sync this PR with this (https://github.com/Cloud-CV/EvalAI/pull/2630) one once it gets an OK from other mentors.

**Comment by nikochiko** [comment]
Again, for the coverage, 
Capture
looks to be like a mathematical detail as the coverage hasn't changed for any file.
(maybe as lines of code in dramatiq_conf.py < lines of code in celery.py which it replaced)
refer: https://github.com/Cloud-CV/EvalAI/pull/2593#issuecomment-571642846

**Comment by yashdusing** [comment]
PR LGTM :+1:
Can you use the #2630 for the API?

**Comment by nikochiko** [comment]
@yashdusing Sure! I will add the changes. :+1:

**Comment by nikochiko** [comment]
Done! The coverage is also going up now :smile:

**Comment by nikochiko** [comment]
I tried some changes out to check functionality. I've reverted everything though. 
Also added a `time.sleep(0.5)` for tests with processing multiple messages so that the order of processing is maintained.

**Comment by yashdusing** [comment]
LGTM :+1:

**Comment by nikochiko** [comment]
I noticed upon running dramatiq on my end that it needs to run the file with the actual task from the command line for it to be able to work. This is not scalable and with the current changes, the worker doesn't pick up messages from the queue. A more scalable alternative is to use the `django_dramatiq` library instead. 
As it is optimized for django, it would give us an easier time. I tried doing so in https://github.com/Cloud-CV/EvalAI/pull/2583 and it's almost done but there's a seemingly unrelated error popping up in the [Travis](https://travis-ci.org/Cloud-CV/EvalAI/builds/643826872).

If getting this merged is high-priority, we can open up a new issue for it (I am having exams starting this week but will be glad to offer some help if required).

@RishabhJain2018 ?
reference: https://github.com/Cloud-CV/EvalAI/issues/2516

**Pull request closed without merging**
