### PR TITLE
Fix #2241 Allow unverified user to view the challenge

### LINKED ISSUE #2241: Allow unverified user to view the challenge
### Observed Behaviour
If an unverified user tries to view a challenge page, he is not able to do so and is told to verify the email first.

### Expected Behaviour
The unverified user should be allowed to view the challenge page and if he visits the `Participate` tab , an error stating to verify email address should be shown.

@RishabhJain2018 @deshraj

### PR DESCRIPTION
**Pull request by Suryansh5545**
This was a GCI task and was attempted by  me and @danial22373 . I was unable to add the test file for permission.py uncovered line. The file was then added by danial in his pr for the task . But he was unable to resolve the conflict due to time shortage and handed it over to me . So i have added his test file in my branch with my previous code and i now making a single pr to fix this issue .

Changes:-
The unverified user is not allowed to view the participate page also he is shown a notify with error message when he arrive on participate page or click the star button.

Selection_051
Selection_052

### CODE REVIEW

**Comment by Suryansh5545** [comment]
@Sanji515 @Ram51 please take a look

**Comment by Suryansh5545** [comment]
@RishabhJain2018 Sir, is this pr mergeable??

**Comment by Suryansh5545** [comment]
@Rishabhjain2018 Sir please take a look

**Comment by RishabhJain2018** [comment]
Thanks @Suryansh5545 for the mention and the PT. I'll be able to look nat it in a few days.

**Comment by RishabhJain2018** [comment]
Closing this for now #2241

**Pull request closed without merging**
