### PR TITLE
Fix runtime errors while running tests

### LINKED ISSUE #1277: RuntimeWarning: DateTimeField received a naive datetime
This error occurs while running the tests.
See https://stackoverflow.com/questions/18622007/runtimewarning-datetimefield-received-a-naive-datetime
image
Partial solution: change
```
when_made_public=datetime.datetime.now()
```
in tests/unit/jobs/test_views.py to 
```
when_made_public=timezone.now()
```

### PR DESCRIPTION
**Pull request by xamfy**
fixes #1277

### CODE REVIEW

**Comment by xamfy** [comment]
@RishabhJain2018 there are still 3 warnings. I can't find the solution for that.

**Comment by RishabhJain2018** [comment]
@xamfy Can you please paste the screenshot for the warnings.

**Comment by xamfy** [comment]
image

**Comment by RishabhJain2018** [comment]
@xamfy The warnings are due to https://github.com/django/django/blob/1.7/django/db/models/fields/__init__.py#L1219.
Moreover, it is due to the fact that `auto_now_add` in django uses `datetime.datetime.now()`. For more details please refer here https://github.com/django/django/blob/d92b08536d873c0966e8192e64d8e8bd9de79ebe/django/db/models/fields/__init__.py#L1146

So, I think for now we can ignore these warnings. @deshraj What do you say?

**Comment by deshraj** [comment]
No, we should not get these warnings and we should use `timezone.now()` instead of `datetime.datetime.now()`. 

@xamfy this looks good. I am merging this. Thanks for the fix.

**Pull request merged**
