### PR TITLE
[frontendv2]Made web container width dynamic

### PR DESCRIPTION
**Pull request by Alabhya268**
fixes issue  #3243 #3244 .

for screenwidth 1080p-

after
after2

for screenwidth 2160p scaling 100% -
4k

for screenwidth 2160p scaling 200% -
4k2x

Unapproved challenge card -
unapproved2

### CODE REVIEW

**Comment by Alabhya268** [comment]
@RishabhJain2018 @Ram81 , Please review this PR.

**Comment by Alabhya268** [comment]
@Ram81 , Please review this PR.

**Comment by Alabhya268** [comment]
@Ram81 , Ping for review.

**Comment by Ram81** [comment]
@Alabhya268 how was this tested? Can you share the steps. I am testing by changing browser zoom property and it looks like these changes have messed up the original style. You can see the current style and expected one in the screenshots.

Expected:
Screen Shot 2021-03-08 at 7 00 59 PM

From the PR:

Screen Shot 2021-03-08 at 7 02 03 PM

**Comment by Ram81** [comment]
@Alabhya268 you can send a separate PR for #3244.

**Comment by Alabhya268** [comment]
@Ram81, this issue is now fixed.
 Webcontainer for Frontendv2 is now dynamic.

Please have a look at this PR again.

These are image and video taken after fix just now.


https://user-images.githubusercontent.com/57143358/110331799-907ad580-8045-11eb-8fe6-a7e8d1ca365d.mp4

**Comment by Alabhya268** [comment]
@Ram81 I've now fixed the issue and challengerow are now dynamic.
It turned out that ```All challenges``` page challenge card and other pages challege card were using different classes.

Please look at img and video . These are taken just now after fixing this issue.

https://user-images.githubusercontent.com/57143358/110333113-3844d300-8047-11eb-89ff-1ed6338bade3.mp4

**Comment by Alabhya268** [comment]
> @Alabhya268 you can send a separate PR for #3244.

Changes that are necessary to fix #3243 also fixes #3244 .

**Comment by Ram81** [comment]
@Alabhya268 I still see the same behavior 
Screen Shot 2021-03-11 at 12 36 07 AM
Screen Shot 2021-03-11 at 12 36 10 AM

**Comment by Alabhya268** [comment]
Interesting, its working fine in mine. Let me check it .

**Comment by RishabhJain2018** [comment]
Hi @Alabhya268,
Thank you for the effort but it is a design choice. We actually don't want to make the challenge cards scale dynamically. We would like to keep it centered only.

Please feel free to pick up another issue. Also, please be on the lookout as @Ram81 will open more issues in the next few days.

**Pull request closed without merging**
