### PR TITLE
Added New Design to Host button.

### PR DESCRIPTION
**Pull request by RishabhJain2018**
#432 . @aka-jain Please review the PR.
new

### CODE REVIEW

**Comment by aka-jain** [comment]
@RishabhJain2018 : I think we are not on the same page. We just want to make our components first like button, links, color etc. There is no need to change current website. Just make a test file in which every component placed. I hope you are getting me.

**Comment by RishabhJain2018** [comment]
@aka-jain okk. So, can I create a test file on this path `frontend/new-ui-components.html`.

**Comment by aka-jain** [comment]
Yes @RishabhJain2018. Just work on this file only for now. Will merge it later with new UI

**Comment by aka-jain** [comment]
@parismita : Looks good :)
@deshraj : Merge this please.

**Comment by parismita** [comment]
??

**Comment by aka-jain** [comment]
Sorry for the wrong comment.

**Pull request merged**
