### PR TITLE
Conent center on challenge page

### PR DESCRIPTION
**Pull request by gautamjajoo**
Content is centered on challenge list and challenge page, same as v1.
@Ram81 @Kajol-Kumari 

Screenshot from 2021-06-06 19-19-09
Screenshot from 2021-06-06 19-16-45

### CODE REVIEW

**Review by Ram81 — CHANGES_REQUESTED** [review]
@gautamjajoo can you share more zoomed out screenshots. 

@Kajol-Kumari  can you test this PR locally

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@gautamjajoo can we please make the changes for `web-container` class in their respective components only instead of the changing it in the base class?

**Comment by gautamjajoo** [comment]
@Kajol-Kumari Actually, the `base.scss` of frontend-v1 also contains the similar classes, therefore I have changed it to make it even with it.

**Comment by gautamjajoo** [comment]
@Ram81 50% zoomed out page
Screenshot from 2021-06-09 13-41-41

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Actually, the `base.scss` of frontend-v1 also contains the similar classes, therefore I have changed it to make it even with it.

I can see the `web-container` class used at multiple places in our frontend_v2, so if we modify it under base class, we might leave some hidden css bugs in there. So, it's recommended to only change the styles of required components.

**Comment by gautamjajoo** [comment]
@Kajol-Kumari Updated the PR by moving the changes to the style of the particular component.

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@gautamjajoo The `create-challenge` page is getting distorted for large screens. Please fix that.

Ref - 
Screenshot 2021-06-10 at 9 34 28 PM

**Comment by gautamjajoo** [comment]
@Kajol-Kumari Updated the PR.

**Review by Kajol-Kumari — APPROVED** [review]
LGTM 👍

**Review by Ram81 — APPROVED** [review]
LGTM 👍

**Pull request merged**
