### PR TITLE
Gulp

### LINKED ISSUE #74: Improve Gulp Watch task to handle remove, delete, and errors in files.
Need to update watch task of gulp  so that it can easily get files update like delete and add.

### PR DESCRIPTION
**Pull request by anweshknayak**
fix #74

### CODE REVIEW

**Comment by anweshknayak** [comment]
@aka-jain please review

**Comment by aka-jain** [comment]
@anweshknayak : have to do some small fixes. Please have a look at comments.

**Comment by anweshknayak** [comment]
@aka-jain done

**Comment by aka-jain** [comment]
@anweshknayak : Thanks for integrating this feature.
@deshraj : Merge this PR please.

**Pull request merged**
