### PR TITLE
Fix #3210: Fix padding of placeholder in leaderboard

### LINKED ISSUE #3210: [Frontend_v2] Fix padding of select phase placeholder on Leaderbord page
### Description

The padding of the placeholder `Challeng Phase` is inconsistent in the dropdown on Leaderboard page. Following screenshots show the current style :

No phase is selected:
Screen Shot 2021-02-04 at 7 27 15 PM

Phase selected:

Screen Shot 2021-02-04 at 7 27 18 PM

Padding is expected to be same for both placeholder text and selected phase name in the dropdown.

### PR DESCRIPTION
**Pull request by burnerlee**
fixes #3210

### CODE REVIEW

**Comment by burnerlee** [comment]
Before fix:
Screenshot from 2021-02-05 00-33-29
After Fix:
Screenshot from 2021-02-05 00-33-29

**Comment by burnerlee** [comment]
Before fix:
Screenshot from 2021-02-05 00-59-42
After fix:
Screenshot from 2021-02-05 00-59-15

**Comment by Alabhya268** [comment]
@burnerlee , It looks good, it would be even better if bottom padding is added to match the height same as when item is selected from list. :+1

**Review by Ram81 — CHANGES_REQUESTED** [review]
@burnerlee we need all 4 paddings of placeholder to be consistent with selected option. Can you please fix the same

**Comment by burnerlee** [comment]
> @burnerlee we need all 4 paddings of placeholder to be consistent with selected option. Can you please fix the same

yes, I was trying to fix this. But it took me a lot of time but I wasn't able to achieve the required result with a good code because of the type of nesting for the placeholder div. I'll look for a better solution for this by tomorrow, couldn't figure this out today

**Comment by Ram81** [comment]
@burnerlee any updates?

**Comment by burnerlee** [comment]
Oh oh sorry, missed this thing completely.. I'll fix it now

**Comment by burnerlee** [comment]
@Ram81 @Alabhya268 , I tried a lot, but could not change the bottom padding. I need to change the position of  label with `mat-form-field-label` class but 
```
.mat-form-field-label{
 //css props here
}
```
does not make css change to this component. Could you please help me in this. If I would be able to change css of this component I would be able to achieve the result.

**Comment by Alabhya268** [comment]
@burnerlee , Try changing css using this

```
::ng-deep .mat-select-placeholder {
  padding-bottom: 10px;
}
```

**Comment by burnerlee** [comment]
> @burnerlee , Try changing css using this
> 
> ```
> ::ng-deep .mat-select-placeholder {
>   padding-bottom: 5px;
> }
> ```



> @burnerlee , Try changing css using this
> 
> ```
> ::ng-deep .mat-select-placeholder {
>   padding-bottom: 5px;
> }
> ```

hey @Alabhya268 , thank you so much. Yes it worked for me. Didn't have an idea about ::ng-deep, I'll read about it. But thank you so much, had put in a lot of time without the desired result

**Comment by burnerlee** [comment]
Screenshot from 2021-02-27 00-58-53
Bottom padding fix as well now, @Ram81

**Review by Ram81 — APPROVED** [review]

**Pull request merged**
