### PR TITLE
Test for update user API endpoint

### LINKED ISSUE #864: Restrict the update profile API Endpoint from updating username
Currently, django-rest-auth provides the functionality to update the username with the update profile API Endpoint. We want to restrict this since we don't want a user to update his username once he has created his account. 

For more details about the API endpoint, look at http://django-rest-auth.readthedocs.io/en/latest/api_endpoints.html#basic

### PR DESCRIPTION
**Pull request by xamfy**
Tests for #1269 that fixes #864 
Test case to check whether username can be updated through API or not.

### CODE REVIEW

**Comment by xamfy** [comment]
@RishabhJain2018 Done

**Comment by isht3** [comment]
@xamfy A few things to note down.

- Squash the two commits into one.
- Tests should not be declared in the Base Class, you can declare a new class. (See the other tests for reference)
- I tested your code, and I got this `AssertionError: Couldn't retrieve content: Response code was 301 (expected 200)`. It's because, the you shouldn't do a `POST`, It should be either `PUT` or `PATCH`.

**Comment by isht3** [comment]
@xamfy And you don't have to close the PR every time you make changes, you can push to the same branch in your fork, and the PR will be automatically updated. :smile:

**Comment by xamfy** [comment]
@isht3 The tests work fine for me(I've used put)
I didn't close the PR, it got closed automatically when I force pushed
Can you tell how to squash two commits into one
I'll make a new class for the test

**Comment by xamfy** [comment]
@isht3 The tests work fine for me(I've used put)
I didn't close the PR, it got closed automatically when I force pushed
Can you tell how to squash two commits into one
I'll make a new class for the test

**Comment by isht3** [comment]
@xamfy https://stackoverflow.com/questions/2563632/how-can-i-merge-two-commits-into-one

**Comment by RishabhJain2018** [comment]
LGTM :) Thanks for the fix!

**Comment by deshraj** [comment]
@xamfy: seems like the Travis Checks are failing. Can you please fix them?

**Comment by RishabhJain2018** [comment]
@deshraj The travis checks are failing because the PR contains only the tests . The serializer code is in the PR #1269

**Pull request merged**
