### PR TITLE
Added cmd to add upstream

### PR DESCRIPTION
**Pull request by Alabhya268**
Command to add upstream in contributing.md (So that you fetch from the master repository, not your clone, when running git fetch et al.)

### CODE REVIEW

**Comment by Alabhya268** [comment]
@RishabhJain2018 Please review this PR.

**Review by RishabhJain2018 — APPROVED** [review]

**Comment by Alabhya268** [comment]
@RishabhJain2018 , Is there anything else that needs to be changed?

**Comment by RishabhJain2018** [comment]
No, it looks good.

**Comment by Alabhya268** [comment]
> No, it looks good.

@RishabhJain2018 then could you please merge this PR. :)

**Comment by RishabhJain2018** [comment]
Please let the build complete and then will merge it. Meanwhile, feel free to take any other issue.

**Pull request merged**
