### PR TITLE
Use new style exceptions and define xrange() for Python 3

### LINKED ISSUE #1241: Port the Code to Python 3 and make it Python 2 compatible.
If this issue will be accepted I'll be glad to work on this.

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #1241 (partially)
* New styles exceptions work on both Python 2 and Python 3.
* xrange() was removed in Python 3.  When on Python 3, use range() instead..

### CODE REVIEW

**Comment by deshraj** [comment]
Merging this one. Thanks @cclauss. :)

**Comment by deshraj** [comment]
@cclauss: would you mind adding the test case for the same?

**Comment by cclauss** [comment]
#1331 proves the need for these changes under Python 3

**Comment by cclauss** [comment]
@deshraj What happened on [this merge](https://github.com/Cloud-CV/EvalAI/pull/1260#issuecomment-338327220)?

**Comment by deshraj** [comment]
Sorry @cclauss, I missed this somehow. Merging now.

**Comment by deshraj** [comment]
@cclauss merging this but can you please add unittest for the same in a different pull request?

**Pull request merged**
