### PR TITLE
Fixed SelectPhase Private badge CSS

### LINKED ISSUE #3212: [Frontend_v2] Fix Private tag alignment on Leaderboard page
### Description

Screenshot_2020-10-11_at_11 30 29_AM

The private tag for a phase split is misaligned. It should appear next to the challenge phase split name itself and not downwards.

### PR DESCRIPTION
**Pull request by ShauryaAg**
Fixes #3212

Fixed `.private-badge` CSS in `selectphase.component.scss`

After Fix:
image

### CODE REVIEW

**Review by Ram81 — CHANGES_REQUESTED** [review]
@ShauryaAg can you share a screenshot with a phase split name that overflows in the select option. I want to see whether this change will work when the phase split name is quite large. You can try creating a challenge phase split with 40-50 chars

**Comment by ShauryaAg** [comment]
@Ram81, Here's a GIF that shows the behavior when the Phase Split name is set to `Megan Phase - Some Long String that is more 40 or 50 characters in length`
localhost_4200_challenge_20_leaderboard_80 - Google Chrome 2021-02-08 18-33-13

**Comment by Ram81** [comment]
@ShauryaAg when phase has more than 30-40 characters the phase split name should wrap instead of appearing below the private tag. Can you please fix that

**Comment by ShauryaAg** [comment]
After Fix:
image

**Review by Ram81 — CHANGES_REQUESTED** [review]
@ShauryaAg I can see that the dropdown is overflowing to the component next to it horizontally. Can we please fix that? the components overflowing is bad UX. Also once you fix it please post a gif showing a phase split name with ~15-20 characters and a phase split with < 10 characters.

**Comment by ShauryaAg** [comment]
Sure. Here's a GIF after fixing the overflow problem with 3 phase splits for `>40-50 chars`, `15 chars`, and `<10 chars`
localhost_4200_challenge_20_leaderboard_80_gif

**Review by Ram81 — APPROVED** [review]
LGTM 👍

**Review by RishabhJain2018 — APPROVED** [review]

**Comment by RishabhJain2018** [comment]
@ShauryaAg Can you please resolve the conflicts here?

**Comment by ShauryaAg** [comment]
Sure @RishabhJain2018. It's done.

**Pull request merged**
