### PR TITLE
Fix font inconsistencies

### LINKED ISSUE #3338: [Frontend V2] Set font-weight 300 and reduce width of row separator on My submissions and All submissions tab
### Description

Font-weight is inconsistent on the `My submissions` and `All submissions` page. We should set font-weight: 300 for both tabs and reduce the width of row separator. Refer to frontend v1 css for the style.

### PR DESCRIPTION
**Pull request by gautamjajoo**
Fixes #3338 .
Fix font inconsistencies on my submission and all submissions page.

screencapture-0-0-0-0-4200-challenge-20-my-submissions-2021-03-24-13_04_05

### CODE REVIEW

**Comment by Ram81** [comment]
@gautamjajoo this looks pretty good. Nice work. Can you also share a screenshot of `All submissions` page. Can we also make this change for all tabs on challenge page i.e `Submit`, `Evaluation`, `Leaderboard`, `Overview` and `Settings`

**Comment by gautamjajoo** [comment]
@Ram81 I haven't done the changes to the row-separator. Would this look better or we should have a line above the expanded row as well?

**Comment by gautamjajoo** [comment]
@Ram81 Also, there are many places where we are using grey colour on the main text and in frontend-v1 we have black colour. So what should we use?

For ex: The heading of the column on `my-submission` page.

**Comment by Ram81** [comment]
@gautamjajoo  we should use black color for the text same as frontend v1.

>@Ram81 I haven't done the changes to the row-separator. Would this look better or we should have a line above the expanded row as well?

We can add this in a separate PR. Let's just fix the issues with font in this PR 🙂

**Comment by gautamjajoo** [comment]
#### All Submission Page
all-submission



#### Submit page
Screenshot from 2021-03-25 22-24-32



#### Leaderboard
Screenshot from 2021-03-25 22-54-32



#### Phase Select Option
Screenshot from 2021-03-25 23-00-42

**Comment by Ram81** [comment]
@gautamjajoo can you also share a screenshot of overview page. Another test case is to use challenge host account and check `Manage` and `Settings` tab. We also create a default host account when you start the containers. You can use username `host` and password `password` to test this.

**Comment by gautamjajoo** [comment]
@Ram81 There is no change for `Overiew` and  `Settings` page as it same as v1.

**Review by Ram81 — APPROVED** [review]
LGTM 👍

**Comment by RishabhJain2018** [comment]
@gautamjajoo Can you please resolve the conflicts here?

**Comment by gautamjajoo** [comment]
@RishabhJain2018 @Ram81 While resolving the conflicts, I just looked that I have once again added the `filter submission` for `team name` on `my-submission` page which was earlier resolved. Should I make a new PR?

So sorry for the inconvenience! :(

**Pull request merged**
