### PR TITLE
Fix #1876 : Filename too long issue displayed on Frontend

### LINKED ISSUE #1876: Display error if filename is too long
**Current Scenario:**
While submitting to EvalAI, if the filename is greater than 100 characters then the submission isn't accepted & no error is being thrown on the front-end, so a participant doesn't get to know about the state of his submission.

**Deliverables:**
Display the error thrown by API on the frontend.

### PR DESCRIPTION
**Pull request by yashdusing**
Issue #1876 states about a bug in the backend that isn't relayed to the front end. PR fixes the issue by checking the length of string before submission.

### CODE REVIEW

**Comment by yashdusing** [comment]
Updated . Is this okay ?

**Comment by yashdusing** [comment]
@deshraj @RishabhJain2018 could you look into the PR ? 
I changed it so that the API message is displayed on frontend

**Comment by RishabhJain2018** [comment]
Yeah, it looks good. Can you please paste the screenshot of the error message displayed.

**Comment by yashdusing** [comment]
screenshot-0 0 0 0-8888-2018 11 18-03-13-12

**Pull request merged**
