### PR TITLE
PR for issue #1733

### PR DESCRIPTION
**Pull request by nikhilmudholkar**
fix for #1733
There are some issues with this which i have mentioned in the comment of the issue

### CODE REVIEW

**Comment by nikhilmudholkar** [comment]
All 367 out of 367 tests have passed. Still, it's failing. Can anyone please look into this?

**Comment by vkartik97** [comment]
@nikhilmudholkar Its failing at [`The command "flake8 ./" exited with 1.
`](https://travis-ci.org/Cloud-CV/EvalAI/builds/492034547#L826)
Flake8 is a took to check code base against coding style (PEP8)
<br>
Just format the File as per the warnings:
```sh
./apps/jobs/views.py:137:1: W293 blank line contains whitespace
./apps/jobs/views.py:139:9: E303 too many blank lines (3)
./apps/jobs/views.py:147:1: W293 blank line contains whitespace
./apps/jobs/views.py:149:9: E303 too many blank lines (3)
./apps/jobs/views.py:159:9: E303 too many blank lines (3)
./apps/jobs/views.py:173:121: E501 line too long (151 > 120 characters)
./apps/jobs/views.py:193:1: E303 too many blank lines (4)
```

**Comment by nikhilmudholkar** [comment]
finally :)

**Comment by gautamjajoo** [comment]
@nikhilmudholkar For the issue related to end date of the challenge, please create a new issue and a separate PR fixing it. Here's the [comment](https://github.com/Cloud-CV/EvalAI/issues/1733#issuecomment-461771682)

**Pull request closed without merging**
