### PR TITLE
EvalAI-ngx

### PR DESCRIPTION
**Pull request by live-wire**
This branch will contain all the changes required in the API for the new [front-end](https://github.com/Cloud-CV/EvalAI-ngx) to go LIVE.
Please have a look @RishabhJain2018 @deshraj

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@live-wire Can you please check why the Travis build is failing? Also, please add a small description about the PR. I didn't get why we need to add this code.

**Comment by RishabhJain2018** [comment]
@live-wire Can you please check why the build is failing?

**Comment by live-wire** [comment]
Hey @RishabhJain2018 I'll update this section asap.

**Comment by deshraj** [comment]
Since we have decided to work on EvalAI-ngx parallelly and will merge with current EvalAI repository once it is ready after this summer, so I am closing this PR for now.

**Pull request closed without merging**
