### PR TITLE
Submission app deleted

### PR DESCRIPTION
**Pull request by AnshulBasia**
#785

### CODE REVIEW

**Comment by TroJan** [comment]
@AnshulBasia : Your test cases are failing because you forgot to remove `submission` app from installed apps in settings. Can you please update settings?

**Comment by AnshulBasia** [comment]
@TroJan  Thanks for telling me.

**Comment by TroJan** [comment]
@AnshulBasia : Can you explain me what is the reason behind removing `jobs/admin.py`?
As per my knowledge it should not be removed but I really want to see your point of view so that I can be confirmed that I am not missing anything.

**Comment by AnshulBasia** [comment]
@TroJan  There was just one reason. Did I misinterpret your statement ?
reason

**Comment by AnshulBasia** [comment]
@TroJan Because you told me to. I have messaged you. Please discuss if possible, Thanks for your time.

**Comment by deshraj** [comment]
It would be great @AnshulBasia if we all can discuss here :) This will make sure that everyone is on the same page.

**Comment by AnshulBasia** [comment]
@deshraj Not a problem. Actually, this was explicitly told to me to remove jobs/admin.py. I may have mis interpreted, that's why, to clear that up, I just want to discuss.

**Comment by deshraj** [comment]
Sounds good. :)

**Comment by TroJan** [comment]
@AnshulBasia : just to clear your doubt. I have asked you to remove `jobs/admin.py` from the PR which you have created earlier. I hope you get my point now.

Also I will suggest you to have a look at [django apps](https://docs.djangoproject.com/en/1.10/ref/applications/).

**Comment by AnshulBasia** [comment]
@TroJan I got you. Thanks for clearing up confusion. Yes, I'll have a look at that in detail.

**Pull request closed without merging**
