### PR TITLE
Fix Animations

### PR DESCRIPTION
**Pull request by gautamjajoo**
Fix animations on Contact Page, Get Involved, and Privacy Policy.
@RishabhJain2018 @vkartik97 @erikaaatan

screencapture-127-0-0-1-8888-contact-2018-10-26-08_17_31
screencapture-127-0-0-1-8888-privacy-policy-2018-10-26-08_28_56
screencapture-127-0-0-1-8888-get-involved-2018-10-26-08_29_13

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@vkartik97 Can you please review it?

**Comment by erikaaatan** [comment]
@RishabhJain2018 @vkartik97 this solution works but it eliminates the animations from the view. Should I approve it?

**Comment by gautamjajoo** [comment]
The landing page also eliminates the animations when seen in mobile view. So, replicated same here.

**Comment by vkartik97** [comment]
@erikaaatan  Animations are eliminated in `/about` for Mobile view.

**Comment by gautamjajoo** [comment]
@deshraj Shoudl I close this PR as #1891 was merged and that have fixed the issue?

**Comment by gautamjajoo** [comment]
Similar changes done in #1891 .

**Pull request closed without merging**
