### PR TITLE
Timeout field in Submission model

### PR DESCRIPTION
**Pull request by anweshknayak**
#362 fixed. @deshraj review please

### CODE REVIEW

**Comment by anweshknayak** [comment]
@deshraj can you help out with the travis-ci error ?

**Comment by TroJan** [comment]
@anweshknayak : when ever you add or update any field in a model, you need to create a corresponding migration file for it. Migration are a way by which django propagates your model changes to the database. 

You can create migrations by running `makemigrations` command.

**Comment by anweshknayak** [comment]
@TroJan Oh I totally forgot. Thanks @TroJan

**Comment by TroJan** [comment]
@anweshknayak : please make this field as `PositiveIntegerField` instead of `TimeField`.

**Comment by anweshknayak** [comment]
@TroJan what about the extra migration files being created? Shall I add git ignore to it ?

**Comment by TroJan** [comment]
@anweshknayak : you have accidentally deleted migration file of other apps and added some migration for other apps. You can abandon this branch and start afresh. just create another branch from master, do the changes,

This issue requires only a single change, where in you will add only `execution_time_limit` as field in models and then corresponding migration file for it.

To avoid touching other app migrations, please pass the name of app explicitly, here in present case it will be 

```
python manage.py makemigrations jobs --name=add_tle_submission_field
```


I hope this clears all your doubt.

**Pull request closed without merging**
