### PR TITLE
Migration from bower to yarn

### PR DESCRIPTION
**Pull request by PalashTanejaPro**
GSoC deliverable from https://github.com/Cloud-CV/GSoC-Ideas/issues/21
Migrated from bower to yarn by moving all packages and dependencies to package.json and creating a symlink to preserve current code.

Tested functionality and everything is working just as before. 
Screenshot from 2019-04-07 13-49-25

### CODE REVIEW

**Comment by PalashTanejaPro** [comment]
@RishabhJain2018 @gautamjajoo :)

**Comment by RishabhJain2018** [comment]
@PalashTanejaPro Can you please resolve the conflicts here?

**Comment by PalashTanejaPro** [comment]
@RishabhJain2018 I merged it with the latest master and fixed the merge conflict.

**Comment by PalashTanejaPro** [comment]
@galipremsagar we can ignore the fsevents warning because that's for setting up symlinks on Mac OS afaik and it's skipped if you're on Linux (which you are at the moment). But for me and other Mac users it's needed to make things work and set up the components folders.

**Comment by RishabhJain2018** [comment]
Hi @PalashTanejaPro,
The PR doesn't work when it gets merged with the latest master. Can you please fix it. Here is the error - 
Screenshot 2019-05-17 at 6 13 05 PM

**Comment by RishabhJain2018** [comment]
@galipremsagar 
> The fsevents mac warning can we ignore? I think we can as I searched the project and see no usages of that package. @RishabhJain2018 what say? or am I missing something on this?

Yes, we can ignore them.

> On the unmet peer dependencies are we going to upgrade?
Yes, but let's merge this first and then we will upgrade.

**Comment by PalashTanejaPro** [comment]
@RishabhJain2018 on it

**Comment by RishabhJain2018** [comment]
@PalashTanejaPro Any updates?

**Pull request closed without merging**
