### PR TITLE
Added backend support for adding a profile picture

### LINKED ISSUE #1777: Add functionality to update the profile picture
**Current Scenario:**
A user can't update his profile picture.

**Deliverables:**
A field on the profile page where a user can upload an image in order to update it.
The screenshot of the Update Profile Page is given below.
screen shot 2018-08-22 at 6 33 23 pm

### PR DESCRIPTION
**Pull request by usmanmuhd**
Fixes #1777

### CODE REVIEW

**Comment by usmanmuhd** [comment]
@RishabhJain2018 please take a look

**Comment by RishabhJain2018** [comment]
@usmanmuhd Can you please check why travis build is failing?

**Comment by usmanmuhd** [comment]
@RishabhJain2018 I have fixed the errors in the tests. Could you please take a look?

**Comment by deshraj** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
