### PR TITLE
Backend: Add unique to codename field in DatasetSplit Model

### PR DESCRIPTION
**Pull request by mayank-agarwal-96**
Fixes issue #917 .

### CODE REVIEW

**Comment by mayank-agarwal-96** [comment]
@deshraj Please check.

**Comment by deshraj** [comment]
@mayank-agarwal-96 can you please name migrations? See https://docs.djangoproject.com/en/1.11/ref/django-admin/#cmdoption-makemigrations-name for more reference.

**Comment by mayank-agarwal-96** [comment]
@deshraj Made the changes.

**Comment by mayank-agarwal-96** [comment]
@deshraj I did the changes. Please check.

**Pull request merged**
