### PR TITLE
Update views.py

### PR DESCRIPTION
**Pull request by rakesh-1601**
error bug fixed

### CODE REVIEW

**Comment by deshraj** [comment]
@rakesh-1601 please check the TravisCI failing tests and fix them. :)

**Comment by rakesh-1601** [comment]
@deshraj sure sir..I will try!!

**Comment by RishabhJain2018** [comment]
@rakesh-1601 Any update on this?

**Comment by rakesh-1601** [comment]
sir any guidelines on how i can check TravisCl build failure

**Comment by RishabhJain2018** [comment]
You can check here https://travis-ci.org/Cloud-CV/EvalAI/jobs/408017197#L708

**Comment by rakesh-1601** [comment]
I have fixed that error...review it

**Comment by deshraj** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
