### PR TITLE
Fix #1980: Fixing Generator Expression Error

### LINKED ISSUE #1980: SyntaxError: Generator expression must be parenthesized
While running `$ python manage.py migrate --settings=settings.dev` in MacOS 10 :
```sh
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/kartik/Documents/Code/EvalAI/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/kartik/Documents/Code/EvalAI/lib/python3.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/kartik/Documents/Code/EvalAI/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/kartik/Documents/Code/EvalAI/lib/python3.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/kartik/Documents/Code/EvalAI/lib/python3.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/kartik/Documents/Code/EvalAI/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 4, in <module>
    from django.contrib.admin.filters import (
  File "/Users/kartik/Documents/Code/EvalAI/lib/python3.7/site-packages/django/contrib/admin/filters.py", line 10, in <module>
    from django.contrib.admin.options import IncorrectLookupParameters
  File "/Users/kartik/Documents/Code/EvalAI/lib/python3.7/site-packages/django/contrib/admin/options.py", line 13, in <module>
    from django.contrib.admin import helpers, widgets
  File "/Users/kartik/Documents/Code/EvalAI/lib/python3.7/site-packages/django/contrib/admin/widgets.py", line 152
    '%s=%s' % (k, v) for k, v in params.items(),
    ^
SyntaxError: Generator expression must be parenthesized
```

### PR DESCRIPTION
**Pull request by vkartik97**
Closes: #1980 

Deliverables:
- [x] Solved `SyntaxError: Generator expression must be parenthesized` in MacOS by Updating Django to 1.11.17 - [Source](https://stackoverflow.com/a/48822656)

### CODE REVIEW

**Comment by kurianbenoy** [comment]
Hey @vkartik97. This error is due to [Python3.7](https://stackoverflow.com/questions/51265858/syntaxerror-generator-expression-must-be-parenthesized). I guess recently evalai moved to python3 only, since the latest version of django2 only tries to fix this compatibility bug. I feel maybe it would be better to move to django 2.
What do you think @deshraj @RishabhJain2018

**Comment by vkartik97** [comment]
@kurianbenoy It would be better to wait for Django 2.2(Expected April 2019), which is LTS.

**Comment by deshraj** [comment]
Agree with @vkartik97. It makes a lot of sense to wait for the LTS version to come out.

**Comment by kurianbenoy** [comment]
Yea I agree with @vkartik97. Meanwhile, I checked Django release cycle. According to it support dates for:
- django 1.11 LTS(March 2020)
- django 2.2 LTS(Beyond 2021)
- django 3.0 will be released on 2020

**Pull request merged**
