### PR TITLE
 Fix#2574 Fixed Improper error message in team name

### PR DESCRIPTION
**Pull request by Tanuj22**
#2574

**Changes**

Screenshot from 2020-01-10 22-41-39

All non-english characters input show "Invalid letter is contained" error message.

### CODE REVIEW

**Comment by Suryansh5545** [comment]
@Tanuj22 I am not a mentor . but i will like to suggest that we should do the check in the [API](https://github.com/Cloud-CV/EvalAI/blob/master/apps/hosts/views.py#L32) and then return the response which can be then shown by the onError function . What do you say?

**Comment by Tanuj22** [comment]
@Suryansh5545 Seems to be the better option! Thanks!

**Comment by Suryansh5545** [comment]
@Tanuj22 The error message for improper error message is not displayed. I think you have implemented it in a wrong file. When the create team button is clicked this [API](https://github.com/Cloud-CV/EvalAI/blob/master/apps/hosts/views.py#L213) `create_challenge_host_team` is called. you have to implement it in that and then return the response with error message. also as this is the fix for improper team name can you please add this functionality to participate tab. For this you have to edit this [API](https://github.com/Cloud-CV/EvalAI/blob/master/apps/participants/views.py#L47).

**Comment by Tanuj22** [comment]
@Suryansh5545 I have changes in the model `ChallengeHostTeam`  to accept only english characters which is better than making changes in the API I think. As for adding it in the participate tab I can do that.

**Comment by Suryansh5545** [comment]
@Tanuj22 The error message for invalid character is still the same please fix it. And please update the branch

**Comment by Tanuj22** [comment]
@Suryansh5545 I have checked it again now. Could you recheck?  I am attaching a GIF for the same.

ezgif-7-e645f4a2b945

**Comment by Suryansh5545** [comment]
@Tanuj22 It is working now . :+1:

**Comment by Suryansh5545** [comment]
Now if you can please add this functionality to participate.

**Comment by Tanuj22** [comment]
@Suryansh5545  Done

**Comment by Suryansh5545** [comment]
@Tanuj22 LGTM:+1:


@Sanji515 @Ram81 @RishabhJain2018 @vkartik97 Please take a look

**Pull request closed without merging**
