### PR TITLE
Updated Contribution Guidelines: Added instructions to install HTML/CSS/JS Pretifier.

### LINKED ISSUE #609: Add HTML/CSS/JS pretifier in the Readme.
Please add instruction for installing the `HTML/CSS/JS` pretifier in the` readme `file in order to pretify the frontend code.

### PR DESCRIPTION
**Pull request by RishabhJain2018**
fixes #609. @aka-jain @spyshiv @deshraj  Please review the PR.

### CODE REVIEW

**Comment by deshraj** [comment]
@RishabhJain2018 can you add this in the Contribution Guidelines doc?

**Comment by RishabhJain2018** [comment]
@deshraj ok Sure. So, should I remove it from Readme file?

**Comment by deshraj** [comment]
Yes please.

**Comment by RishabhJain2018** [comment]
@deshraj @aka-jain @spyshiv Please review.

**Comment by deshraj** [comment]
Looks good.

**Pull request merged**
