### PR TITLE
Fix #3701 Added Search Bar to both Frontend_v2 and v1

### LINKED ISSUE #3701: [FrontendV2] Add search option on all challenges and hosted challenges page
### Description

Add support to search challenges by name on the `All challenges` and `Hosted challenges` page.

### PR DESCRIPTION
**Pull request by Suryansh5545**
Fix #3701 Added a search option on all challenge and hosted challenge page
Peek 2023-02-26 13-03

Peek 2023-02-26 16-03

### CODE REVIEW

**Comment by Suryansh5545** [comment]
@gchhablani  Hello Sir, Can you review this PR? 
Also i wanted to ask if Frontend_V2 is no longer in roadmap for evalai as it was deprecated from the development branch in commit #3810 ? or was it due the failing test case?

**Comment by gchhablani** [comment]
@Suryansh5545 Thanks a lot for this PR!
This is great work.
Yes, `frontend_v2` is not being pursued. Currently, there are no plans to revive it.
@Ram81 @rishabh How doees this look?

**Comment by Suryansh5545** [comment]
@gchhablani Should i remove the v2 code and push the v1 changes for search or should i close the PR as we already have  #3898 issue?

**Comment by Suryansh5545** [comment]
Closing in favor of #3927

**Pull request closed without merging**
