### PR TITLE
Remove unnecessary condition from my-submissions page

### PR DESCRIPTION
**Pull request by gautamjajoo**
`filterByTeamName` API logic is not required on `my-submissions` page since we are not filtering anything, hence removed the check.

Also, instead of using `localhost:8000`, changed it to environment variable as we use in `all-submissions` page.

### CODE REVIEW

**Comment by Ram81** [comment]
@gautamjajoo could you describe the changes once. Are you just removing the `filterByTeamName` API logic from `My submissions` page? If yes, please update the description with that.

**Comment by gautamjajoo** [comment]
@Ram81 Updated the description

**Comment by Ram81** [comment]
@gautamjajoo can you force push a commit to re-run the travis build

**Comment by gautamjajoo** [comment]
@Ram81 Updated the branch

**Review by Ram81 — APPROVED** [review]

**Review by RishabhJain2018 — APPROVED** [review]

**Pull request merged**
