### PR TITLE
Fix #3157: Show selected submission details in 3 columns

### LINKED ISSUE #3157: [FrontendV2] Show selected submission details in 3 columns
### Description

When a submission is selected on the `My Submissions` tab we currently divide the fields into two columns. The metadata fields should be shown in 3 columns for meta fields in each column.

Here is the current screenshot for reference

Screen Shot 2021-01-20 at 9 38 18 PM

Expected:

Column 1 fields: Team Name, Method Name, Method Description, Project Url, Publication URL
Column 2 fields: Status, Submitted At, Execution Time
Column 3 fields: Show on Leaderboard, Baseline, Edit Submission details

### PR DESCRIPTION
**Pull request by burnerlee**

### CODE REVIEW

**Comment by Ram81** [comment]
@burnerlee can you share a screenshot of the UI after the fix

**Comment by burnerlee** [comment]
> @burnerlee can you share a screenshot of the UI after the fix

Oh sorry, I posted the screenshot in the issue itself. I'll upload it here too

**Comment by RishabhJain2018** [comment]
@burnerlee You should also write a PR description for every PR you open like what issue it is fixing and the screenshot from before and after the issue.

**Comment by gautamjajoo** [comment]
@burnerlee When the screen size is small, the line is vertical and not changing to horizontal.

Screenshot from 2021-01-22 14-20-13

**Comment by burnerlee** [comment]
Oh sorry didn't check that, could you list out some screen sizes I must test frontend on for future and this change?

**Comment by gautamjajoo** [comment]
@burnerlee I mostly drag and check on chrome devtools and also using show media queries and device lists.

**Comment by burnerlee** [comment]
Oh cool, I'll just make this change by tomorrow. Thank you so much

**Comment by RishabhJain2018** [comment]
@burnerlee Any updates on this?

**Comment by burnerlee** [comment]
Yeah I'll be continuing my work today, exams got rescheduled and I had a lot of load, I'm really sorry

**Comment by burnerlee** [comment]
screenshots before fix
Screenshot from 2021-01-26 15-33-23
Screenshot from 2021-01-26 15-05-32

**Comment by burnerlee** [comment]
screenshot after fix:
Screenshot from 2021-01-26 15-29-48
Screenshot from 2021-01-26 15-30-04
Screenshot from 2021-01-26 15-30-10

**Comment by burnerlee** [comment]
@Ram81

**Review by Ram81 — COMMENTED** [review]
LGTM 👍. @RishabhJain2018 can you take a look

**Comment by RishabhJain2018** [comment]
> https://user-images.githubusercontent.com/55936223/105830876-0c681380-5fec-11eb-9284-ce0076130a45.png

@burnerlee Can we please do 3,3,3 in each column?

**Comment by burnerlee** [comment]
Yeah sure, I'll just do

**Comment by Ram81** [comment]
@RishabhJain2018 should we also put the edit logo before the label `Edit submission details` to make it consistent with `Show on Leaderboard` and `Baseline` options?

**Comment by RishabhJain2018** [comment]
Yes, that makes sense.
cc: @burnerlee

**Comment by burnerlee** [comment]
Screenshot from 2021-01-26 23-19-38
@RishabhJain2018

**Comment by burnerlee** [comment]
Screenshot from 2021-01-26 23-19-38
@RishabhJain2018

**Review by RishabhJain2018 — APPROVED** [review]

**Pull request merged**
