### PR TITLE
Worker: Add tests for download_and_extract_file

### PR DESCRIPTION
**Pull request by nikochiko**
As a Google Code-In task

Additions proposed:
1. Add unit test for `download_and_extract_file` function (from submission_worker) when the function works as expected.
2. Add unit test for `download_and_extract_file` when downloading fails with an exception.

### CODE REVIEW

**Comment by yashdusing** [comment]
LGTM 👍

**Comment by pushkalkatara** [comment]
Looks good to me too :+1:

**Comment by RishabhJain2018** [comment]
@nikochiko Can you please resolve the conflicts here?

**Comment by nikochiko** [comment]
@RishabhJain2018 Resolved conflicts :+1:

**Comment by nikochiko** [comment]
@yashdusing @pushkalkatara Can I get an update on the GCI page?

**Pull request merged**
