### PR TITLE
[REVIEW PENDING] Fix #2033 -Add the API call to get team name for current challenge & Modify "My Submissions" tab.

### LINKED ISSUE #2033: Display the participant team name by which a participant participates in a challenge
## Current Behaviour
In the current setup, a participant doesn't know the participant team by which they have participated until they select the submissions under `My Submissions` Tab.

## Expected Behaviour

The participant team should be constantly visible under the `My Submissions` Tab.

## Deliverables
- [ ] Add an API to fetch the participant team of the user corresponding the challenge.
- [ ] Write tests for the API
- [ ] Add frontend code in `My Submissions` Tab to display the participant team of the user for the corresponding challenge.
- [ ] Paste a screenshot of the UI with the PR

Please feel free to ask if you have any doubts!

### PR DESCRIPTION
**Pull request by KhalidRmb**
(Fixes #2033 )
**Deliverables:** 
- [x] Add an API to fetch the participant team of the user corresponding the challenge.
- [x] Write tests for the API
- [x] Add frontend code in My Submissions Tab to display the participant team of the user for the corresponding challenge.
- [x] Paste a screenshot of the UI with the PR
screenshot from 2019-03-04 16-03-32

### CODE REVIEW

**Comment by KhalidRmb** [comment]
@RishabhJain2018 @deshraj Please take a look.

**Comment by rishabhbhardwaj** [comment]
@KhalidRmb Can you please resolve the conflicts?

**Comment by KhalidRmb** [comment]
> @KhalidRmb Can you please resolve the conflicts?

Done!

**Comment by RishabhJain2018** [comment]
@rishabhbhardwaj Can you please review this PR.

**Comment by rishabhbhardwaj** [comment]
@KhalidRmb When the team name is too big then the UI alignment is changing. 
Screen Shot 2019-05-06 at 10 23 52 AM
@RishabhJain2018 Kindly take a call on this. Should we consider trimming the team name in such cases? Rest all looks good to me.

**Comment by galipremsagar** [comment]
> @KhalidRmb When the team name is too big then the UI alignment is changing.
> Screen Shot 2019-05-06 at 10 23 52 AM
> @RishabhJain2018 Kindly take a call on this. Should we consider trimming the team name in such cases? Rest all looks good to me.

I think we should ideally be doing [ellipses](https://css-tricks.com/almanac/properties/t/text-overflow/) in this case.

If that's the way to go we should set max-width as in this demo: https://css-tricks.com/almanac/properties/t/text-overflow/

**Pull request closed without merging**
