### PR TITLE
Fixes error showing bug after a successful submission

### PR DESCRIPTION
**Pull request by yashdusing**
Fixes bug where a submission shows error even after successful submission.

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@yashdusing Can you please give steps on how to reproduce this bug?

**Comment by yashdusing** [comment]
@RishabhJain2018
 Make a faulty submission followed by successful submission. Ideally, after making a successful submission, all previous error messages should have been cleared but that is not the case.

**Comment by RishabhJain2018** [comment]
@yashdusing What do you mean by `faulty submission`?

**Comment by yashdusing** [comment]
@RishabhJain2018 
Any submission that could result in any error. For eg: submission file name too long, phase not selected, etc.

**Comment by RishabhJain2018** [comment]
@yashdusing Can you please resolve the conflicts here?

**Comment by yashdusing** [comment]
@RishabhJain2018 resolved the conflicts. Please review !

**Pull request closed without merging**
