### PR TITLE
[frontendV2] Profile screen frontend fix

### PR DESCRIPTION
**Pull request by Alabhya268**
This PR fixes the issue - #3182 

Before -
cloudcv_profile

After - 
cloudcv_profile2

### CODE REVIEW

**Comment by Alabhya268** [comment]
@RishabhJain2018 , Please have a look at this PR, Let me know if anything else needs to be changed.

**Comment by Alabhya268** [comment]
@Ram81 , Please review this PR.

**Comment by Alabhya268** [comment]
@Ram81 Please review this PR.

**Review by RishabhJain2018 — APPROVED** [review]

**Comment by Alabhya268** [comment]
@RishabhJain2018 , Please merge this PR if nothing else needs to be changed

**Comment by RishabhJain2018** [comment]
@Alabhya268 We will merge this, once the build completes. Since the PR has a label `can-be-merged`, it will be merged soon.

**Pull request merged**
