### PR TITLE
Allow unverified user to view the challenge

### PR DESCRIPTION
**Pull request by daniel22373**
I removed the HasVerifiedEmail permission class from many of the challenges views that were unrelated to participation.

Corresponding GCI task description:
"Observed Behaviour: If an unverified user tries to view a challenge page, he is not able to do so and is told to verify the email first.

Expected Behaviour: The unverified user should be allowed to view the challenge page and if he visits the Participate tab , an error stating to verify email address should be shown.

https://github.com/Cloud-CV/EvalAI/issues/2241"

### CODE REVIEW

**Comment by Suryansh5545** [comment]
#2577

**Comment by Suryansh5545** [comment]
#2577

**Comment by Suryansh5545** [comment]
@daniel22373 I am not a mentor ,But You  have to show the error message when user visits the participate tab and removing HasVerifiedEmail from all function is not required you only need to removed it from one. you can refer to this pr for more info #2577

**Comment by daniel22373** [comment]
> @daniel22373 I am not a mentor ,But You have to show the error message when user visits the participate tab and removing HasVerifiedEmail from all function is not required you only need to removed it from one. you can refer to this pr for more info #2577

Hello, thank you for the heads-up @Suryansh5545 , I really appreciate it! I've been looking at why some of the tests have been failing, but this clears it up. I tested the error message on the local host, and it works as expected. Sorry that the deadline expired, I didn't mean to take your task. I suggest that you ask for an extension next time.

**Comment by Suryansh5545** [comment]
@daniel22373 it's ok. I hope where i failed you will pass.:+1:

**Comment by daniel22373** [comment]
@Suryansh5545 To clarify, in the end, you only made changes to Javascript files, and the last thing to do was to write tests, correct?

**Comment by Suryansh5545** [comment]
@daniel22373 to complete this task you have to remove HasVerifiedPermission from one function which indeed breaks the testing of permission.py file. so yea you have to write a test for it

**Comment by daniel22373** [comment]
> @daniel22373 to complete this task you have to remove HasVerifiedPermission from one function which indeed breaks the testing of permission.py file. so yea you have to write a test for it

I see. I added the updates from your latest commit to my local repository, and I'll work on writing the test(s). I think you were confused because there currently is no test suite for the permission.py file in the Python unit tests folder, so I will try to build it from scratch and see what I need to do. Thanks a lot for the help!

**Comment by daniel22373** [comment]
@Suryansh5545 I am having issues with pushing my commits, so I will close this pull request and start a new one at #2620 .

**Pull request closed without merging**
