### PR TITLE
Change `created_by` field from integer to username in `api/hosts/challenge_host_team/` API endpoint

### PR DESCRIPTION
**Pull request by gauthamzz**
#324 is fixed @deshraj

### CODE REVIEW

**Comment by gauthamzz** [comment]
@deshraj is it okay if change the tests or will that be another pr ?

**Comment by deshraj** [comment]
It should be in the same PR. :-)

**Comment by gauthamzz** [comment]
@deshraj can you tell me if i am going on the right path . I am confused :-1:

**Comment by deshraj** [comment]
@gauthamzz I don't think you need to change so much. Please see this https://github.com/Cloud-CV/EvalAI/blob/master/apps/participants/serializers.py#L18. It will make this task much simpler.

**Comment by gauthamzz** [comment]
Thanks :+1: I was completely lost

**Pull request closed without merging**
