### PR TITLE
Landing Page: Dropdown to user name showing choices.

### LINKED ISSUE #571: Create a dropdown to user name on Landing Page.
When user is logged in then show a down arrow button aside to user's name clicking on which display dropdown having 3 options:
1. Change Password (redirect to change password route)
2. Update Profile (redirect to update profile route)
3. Logout

Let us know in case of any query.

### PR DESCRIPTION
**Pull request by RishabhJain2018**
fixes #571 . @aka-jain @spyshiv Please review the PR.

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@aka-jain @spyshiv Please review the PR.

**Comment by spyshiv** [comment]
LGTM. :+1:  
Please prettify the css

**Comment by RishabhJain2018** [comment]
@spyshiv yeah sure. Moreover, there is no route for the `update profile` in `route.js`. Should I open the issue for the same?

**Comment by aka-jain** [comment]
@RishabhJain2018 Have to do some changes in this PR, I'm working on it form now.

**Comment by RishabhJain2018** [comment]
@aka-jain Yeah Sure.

**Comment by aka-jain** [comment]
@RishabhJain2018 Do small change please:
Proper Indent code, and replace '$' of jquery to angular.element as in contrller it's not good to use jquery. So use angular.element, you can search for angular jqlite for this.

**Comment by RishabhJain2018** [comment]
Okay Sure.

**Comment by RishabhJain2018** [comment]
@aka-jain Please review.

**Comment by aka-jain** [comment]
LGTM :)

**Pull request merged**
