### PR TITLE
Removed unused images

### PR DESCRIPTION
**Pull request by aka-jain**
Removed unused images from directory.

### CODE REVIEW

**Comment by aka-jain** [comment]
Merging this PR.

**Comment by aka-jain** [comment]
@deshraj please check why this is giving travis check error?

**Comment by aayusharora** [comment]
@aka-jain @deshraj One of the test require  deshraj.png which is removed in this PR.
Hence, Travis is giving 
` IOError: [Errno 2] No such file or directory: 'frontend/src/images/deshraj.png`

**Comment by aka-jain** [comment]
Yes @aayusharora .

@deshraj I think "deshraj.png" is not required anymore, so please remove it from test.

**Comment by deshraj** [comment]
Added @aayusharora to review the PR. :) @aayusharora please review.

**Comment by aka-jain** [comment]
@deshraj I think we have to remove the deshraj.png from test and PR is already reviewed.

**Comment by deshraj** [comment]
Fixed the issue. Will merge it once Travis builds are done.

**Pull request merged**
