### PR TITLE
Fix: Added Footer to all Inside Pages(Dashboard View) (#258)

### PR DESCRIPTION
**Pull request by Ram81**
@aka-jain  I've added footer for dashboard view but we need to handle footer separately for homepage, So what should I do ?
Please review & suggest changes if any!

### CODE REVIEW

**Comment by aka-jain** [comment]
@Ram81 : Can you please attach a screenshot of dashboard footer? I think we have to change some css.

**Comment by Ram81** [comment]
@aka-jain  These are for all desktop view,tablet view,mobile view
dashboard1
dashboard2
dashboard3

**Comment by Ram81** [comment]
& this is Homepage one
homepage
will it be right if I would add a css class for homepage footer ?

**Comment by aka-jain** [comment]
@Ram81 : Great, but we need to do some changes. Follow these steps to proceed...
1. Make a separate footer for dashboard so that you don't have to change the home page footer.
2. Flex is not working too, I can see that footer is going up when there is no content present and its not a sticky footer.
3. Don't modify styles on body. Make a separate div or give styles to separate parent because body is inherited from main view (home page)
4. Overall, try to make a flex based footer so that it gets stick to bottom when there is no content in and will move down according to content.

Hope you got my points, try it and let me know if you need more help :)

**Comment by Ram81** [comment]
@aka-jain Done . Pleas Review!

**Comment by aka-jain** [comment]
@Ram81 screenshots please.

**Comment by Ram81** [comment]
homepage
HomePage
dashboard1
Desktop View
dashboard2
Tablet View
dashboard3
Mobile View

**Comment by aka-jain** [comment]
@Ram81: All good, but why header of dashboard view is different than original one. I mean home and evalai link is coming down, have you done these changes to header?

**Comment by Ram81** [comment]
No,I didn't change anything to header it was like that only from the time I started to work on it!

**Comment by aka-jain** [comment]
Okay, will see it. Great work. Thanks :)
@deshraj : merge this PR please.

**Pull request merged**
