### PR TITLE
[REVIEW PENDING]Add test case for analytics Api.

### PR DESCRIPTION
**Pull request by RishabhJain2018**
This PR adds the test case for PR #1058 .
@deshraj @taranjeet Please review the PR.

### CODE REVIEW

**Comment by taranjeet** [comment]
@RishabhJain2018 : Will update on this once I have more clarity on what all we need for v1 in analytics. Thanks for the help :)

**Comment by taranjeet** [comment]
I think this wont be required as of now, since we are not merging its corresponding api as of now. Thanks for your help @RishabhJain2018 .

**Comment by RishabhJain2018** [comment]
@taranjeet No problem.

**Comment by taranjeet** [comment]
Thanks for the help @RishabhJain2018 . This is actually not required.

**Pull request closed without merging**
