### PR TITLE
Adds UI for showing the submissions count by a participant team in a challenge phase.

### LINKED ISSUE #1173: Add UI for showing submissions count for a participant team.
**Expected:**
Add UI for showing the submissions count by a participant team in that phase.

### PR DESCRIPTION
**Pull request by RishabhJain2018**
fixes #1173 . @deshraj @aka-jain @spyshiv Please review the PR.
1. Screen 1 
screen1
2. Screen 2 
screen3
3. Screen 3
screen4
4. Screen 4
screen5

### CODE REVIEW

**Comment by deshraj** [comment]
@RishabhJain2018 this UI seems too basic to me. @aka-jain can you please take lead on this and help Rishabh in highlighting it?

**Comment by aka-jain** [comment]
@RishabhJain2018 add the submission count text in dark blue color box as we did for long polling. Also change the text to 'Total Submissions Done: 2'.

**Comment by RishabhJain2018** [comment]
@deshraj @aka-jain Please review.
1. 
screen1
2. 
screen2

**Comment by RishabhJain2018** [comment]
@deshraj Please take a look.
screen1

**Pull request merged**
