### PR TITLE
Remove unused images

### LINKED ISSUE #1004: Remove unused images from frontend directory
There are a lot of images that are not being used at all and are there in the repository. Can we please get rid of those images?

### PR DESCRIPTION
**Pull request by xamfy**
fixes #1004

### CODE REVIEW

**Comment by xamfy** [comment]
@RishabhJain2018 Done with the changes. I couldn't find these files being used so I removed them.

**Comment by RishabhJain2018** [comment]
@xamfy We are using owl.png in 404 page & we may use cloud3.png  and star.gif in future. :)

**Comment by aka-jain** [comment]
@xamfy Please revert back all the images except cloud-4.gif. We need all the images in future.
cc @deshraj @RishabhJain2018

**Comment by xamfy** [comment]
@aka-jain Sure, will do it.

**Comment by RishabhJain2018** [comment]
@xamfy Any update on this?

**Comment by xamfy** [comment]
@RishabhJain2018  Should I just remove only cloud-4.gif?

**Comment by RishabhJain2018** [comment]
@xamfy Yes!

**Comment by xamfy** [comment]
@RishabhJain2018 okay, I'm doing it.

**Comment by xamfy** [comment]
@RishabhJain2018 Done.

**Pull request merged**
