### PR TITLE
 [WIP] - Add Challenge preview mode for the challenge hosts.

### PR DESCRIPTION
**Pull request by isht3**
## Status changed.

Sorry for the delay with this issue. One more part is left to do that is filtering out the submissions of the challenge hosts when the challenge is not published.

### CODE REVIEW

**Comment by isht3** [comment]
@deshraj Can you drop in your thoughts?

**Comment by deshraj** [comment]
In general the code looks good. It seems to be working also. We would want some minor changes in the pull request:

- [ ] Allow the challenge host to submit even when the challenge is published but make sure that their submissions cannot go to the leaderboard while populating the entries in the leaderboard (involves modifying the leaderboard table)
- [ ] Move the My Challenges to a whole new html and add a link to 'My Hosted Challenges' on the sidebar which will be only visible to people when they login. Does that make sense?
- [ ] Add tags like http://materializecss.com/chips.html for showing the status of the challenge like whether it is approved by admin or not  and whether the challenge host has made the challenge public or not.
- [ ] Change the text 'Challenge has not been approve by admin' -> 'Not approved by Admin'
- [ ] Change the text 'Challenge has not been approve by admin' -> 'Approved by Admin'
- [ ] Change the text 'This challenge is not published' -> 'Not published'
- [ ] Change the text 'This challenge is published' -> 'Published'

**Comment by isht3** [comment]
@deshraj understood.

**Comment by isht3** [comment]
@deshraj @RishabhJain2018 Sorry for the delay but this issue keeps bothering me
```
[20:52:26] Using gulpfile ~/evalai/gulpfile.js
[20:52:26] Starting 'dev:runserver'...
[20:52:26] Starting 'dev'...
[20:52:26] Starting 'clean'...
[20:52:26] Finished 'clean' after 14 ms
[20:52:26] Starting 'css'...
[20:52:26] Starting 'js'...
[20:52:26] Starting 'html'...
[20:52:26] Starting 'images'...
[20:52:26] Starting 'vendorjs'...
[20:52:26] Finished 'vendorjs' after 23 ms
[20:52:26] Starting 'vendorcss'...
[20:52:26] Finished 'vendorcss' after 3.53 ms
[20:52:26] Starting 'fonts'...
[20:52:26] Starting 'configDev'...
[20:52:26] Finished 'configDev' after 1.43 ms

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/rustbucket/evalai/node_modules/optipng-bin/vendor/optipng ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
Any ideas?

**Comment by deshraj** [comment]
Try this command: `npm rebuild`

If this doesn't work, please update your node and npm version.

**Comment by isht3** [comment]
@spyshiv @deshraj Thanks! It worked.

**Comment by isht3** [comment]
@deshraj @spyshiv I've added the required changes. Can you drop thoughts on how it looks? :smile:

**Comment by isht3** [comment]
@deshraj The first issue you mentioned, I've already implemented that check on the Submission Worker. It ignores all the submissions from the challenge host teams. That was the intended behaviour, yes?

**Comment by deshraj** [comment]
> @deshraj The first issue you mentioned, I've already implemented that check on the Submission Worker. It ignores all the submissions from the challenge host teams. That was the intended behaviour, yes?

Ideally their submissions should get evaluated but the results should not be published on the leaderboard. You don't have to worry about it since I am working on it and should push soon as another pull request. Please do look at it. You will learn a few things which will enhance your skills. :) 

Thanks again for getting this done.

**Pull request merged**
