### PR TITLE
Setup "Deploy to Heroku"

### PR DESCRIPTION
**Pull request by gautamjajoo**
With reference to #1339 . Created a "Deploy to Heroku" option for EvalAI.
@RishabhJain2018 @aka-jain

### CODE REVIEW

**Comment by trexdinosaur** [comment]
@gautamjajoo have you tested this? I'm not sure if this is enough to run on Heroku. AFAIK, to setup oneclick deployment you have to define env vars and the configuration to setup the app.

**Comment by aka-jain** [comment]
@gautamjajoo there are only UI cahnegs then how this PR works for Set for Heroku? I didn't get this. Please recheck the title or commits.

**Comment by gautamjajoo** [comment]
@aka-jain Oh! There was some error when I made the PR i had setup the Heroku button.

**Comment by aka-jain** [comment]
Please create a new PR, I'm closing this.

**Pull request closed without merging**
