### PR TITLE
Fix #1338: uses main-header instead of sim-header.

### LINKED ISSUE #1338: Navigation menu is not coming on mobile after login.
Navigation menu icon is not coming up on mobile for logged in user.

### PR DESCRIPTION
**Pull request by AmosHason**
#1338

### CODE REVIEW

**Comment by deshraj** [comment]
@AmosHason can you please paste screenshot here?

**Comment by AmosHason** [comment]
@deshraj I will paste later when I get back home.

**Comment by AmosHason** [comment]
Desktop:

image

Mobile:

image

image

New sign up icon (it was logout icon before):

image

By the way, I think that the line in bold in the menu should reflect the current page (currently "Home" is always the line in bold). I'm not sure how exactly it's intended to be.

**Comment by AmosHason** [comment]
Also there is an issue with the desktop view of main-header that should be addressed afterwards:

Log in -> Push "Hi" button -> Push "Dashboard" button -> Push "Hi" button (**view does not change**) -> Push "Hi" button again (view changes)

**Comment by aka-jain** [comment]
@AmosHason don't change the header instead implement that menu icon in new header.

**Comment by AmosHason** [comment]
@aka-jain Are you sure? It's inconsistent this way. It doesn't make sense to not put the logout button where the login button is located.

**Comment by aka-jain** [comment]
@AmosHason Hi, sorry for the late response. 
Our design is settled like that we have to use two types of header. One is for landing page and another one is for dashboard. You the logged in user will have different experience as compared to non logged in user. Hope you understand.
So, please do the required changes. Thanks.

**Comment by aka-jain** [comment]
Closing this PR as there is no response and there is no need of changes that has been done in this PR 
cc @RishabhJain2018 @deshraj

**Pull request closed without merging**
