### PR TITLE
Fix inconsistent padding on Submit page.

### LINKED ISSUE #3206: [Frontend_v2] Fix inconsistent padding on Submit page
### Description

The padding for the list of phases and submission meta attributes is inconsistent on the challenge submit page. It should be the same for the whole page.

Refer the screenshot:

Screen Shot 2021-02-03 at 4 59 36 PM

### PR DESCRIPTION
**Pull request by Alabhya268**
Fixes #3206
Before -

106897118-81d49200-6718-11eb-9df0-12f0b9e1e3ba

After -

106932818-32a15800-673e-11eb-893c-48d70a7d4b55

### CODE REVIEW

**Comment by Alabhya268** [comment]
@Ram81 @RishabhJain2018 , Please review this PR, Let me know if anything needs to be changes.

**Comment by Ram81** [comment]
@Alabhya268 it looks like padding between list of phases option has increased based on your screenshots. Can you please fix it.

**Comment by Alabhya268** [comment]
> @Alabhya268 it looks like padding between list of phases option has increased based on your screenshots. Can you please fix it.

**Comment by Alabhya268** [comment]
> @Alabhya268 it looks like padding between list of phases option has increased based on your screenshots. Can you please fix it.

Sure

**Comment by Alabhya268** [comment]
> > @Alabhya268 it looks like padding between list of phases option has increased based on your screenshots. Can you please fix it.

Sure.

**Comment by Alabhya268** [comment]
paddings

@Ram81 , Now padding between phase list is same as frontend.

**Review by Ram81 — COMMENTED** [review]
@Alabhya268 can you share a screenshot of complete page. Rest of it LGTM

**Comment by Alabhya268** [comment]
@Ram81, This is screenshot of fullpage.

submit

**Review by Ram81 — APPROVED** [review]
LGTM 👍

**Comment by Alabhya268** [comment]
@RishabhJain2018 , Could you please also "can be merged" this PR.

**Review by RishabhJain2018 — APPROVED** [review]

**Comment by Alabhya268** [comment]
@RishabhJain2018 , Could you please merge this PR .

**Comment by Alabhya268** [comment]
@RishabhJain2018 , This PR has "can be merged" tag for a while now, Could you please merge this PR : )

**Comment by Alabhya268** [comment]
@RishabhJain2018 .

**Comment by Alabhya268** [comment]
@RishabhJain2018 , Ping for this PR.

**Pull request merged**
