### PR TITLE
[Refactor Code] Remove unused services and imports

### PR DESCRIPTION
**Pull request by gautamjajoo**
This PR removes unused imports increasing the bundle size and thus the time to load. Also removes the unused services.

@Ram81 @Kajol-Kumari

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @gautamjajoo as we are doing the code cleanup here so can we please fix the warning as well that we get while logging in?
steps to see the warning-
1. Go to login Page
2. Open up the console
3. Enter credentials and hit `login` button

ref -
Screenshot 2021-07-25 at 9 22 19 PM

**Comment by gautamjajoo** [comment]
@Kajol-Kumari I am opening up a separate PR for it. This issue is ony for `dev` mode and will not be there in production. 
This is on the `all-challenge-list` page.

**Comment by gautamjajoo** [comment]
@Kajol-Kumari I have fixed the above issue in [this PR](https://github.com/Cloud-CV/EvalAI/pull/3550). This PR can be reviewed as well.

**Comment by Kajol-Kumari** [comment]
Instead of manually finding and doing the cleanups everytime. Can we please add the ` "no-unused-variable": true`  and `  "noUnusedLocals": true` in our `tslint.json` file of frontend_v2 ?

\cc: @Ram81 @RishabhJain2018

**Comment by gautamjajoo** [comment]
@Kajol-Kumari I have used this in `tsconfig.json` and checked the errors,
```
"compilerOptions": {
  "noUnusedLocals": true,            /* Report errors on unused locals. */
  "noUnusedParameters": true     /* Report errors on unused parameters. */
}
```

I have added the above rules mentioned in `tslint.json`

**Comment by gautamjajoo** [comment]
@Kajol-Kumari There are some issues when we add these in `tsconfig.json` becuase we are using some services while it is showing error. Also `tslint` is deprecated now, we can try to move to `eslint` as well?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari There are some issues when we add these in `tsconfig.json` becuase we are using some services while it is showing error. Also `tslint` is deprecated now, we can try to move to `eslint` as well?

@gautamjajoo let's not do it rn. As per the scope of this PR adding it under tslint is also fine.

**Review by Kajol-Kumari — APPROVED** [review]
LGTM 👍

**Review by Ram81 — APPROVED** [review]
LGTM

**Review by RishabhJain2018 — APPROVED** [review]

**Pull request merged**
