### PR TITLE
Fix #2046: Center align the footer of dashboard when viewed below med…

### LINKED ISSUE #2046: Center align the footer of dashboard when viewed below medium screen
The dashboard footer be aligned properly as in the homepage when viewed below medium screen size.
@deshraj @RishabhJain2018 

<table border="0">
<tr>
<td width="300">
<p align="center"><b> Observed </b></p>

</td>
<td width="300">
<p align="center"><b> Expected </b></p>

</td>
</tr>
</table>

### PR DESCRIPTION
**Pull request by Sanji515**
Fix #2046 
**Now the footer in Dashboard page is centrally aligned.**

### CODE REVIEW

**Comment by Sanji515** [comment]
@RishabhJain2018 Please Review.

**Comment by RishabhJain2018** [comment]
@Sanji515 Can you please paste a screenshot of it.

**Comment by Sanji515** [comment]
screenshot 138

@RishabhJain2018 Here's the screenshot of the dashboard.

**Comment by Sanji515** [comment]
@RishabhJain2018 Please review.

**Pull request merged**
