### PR TITLE
#1456 Fixed Updated Text

### PR DESCRIPTION
**Pull request by gautamjajoo**
Made the link blue coloured and added some more description for EvalAI!! #1456 Fixed!!
@RishabhJain2018 @aka-jain

### CODE REVIEW

**Comment by aka-jain** [comment]
Is there any issue opened for this? @gautamjajoo

**Comment by gautamjajoo** [comment]
@aka-jain No!!

**Comment by aka-jain** [comment]
So why you have opened this? Basically I need to know the context for this Pull Request. Somebody told you or you have opened it by yourself?

**Comment by gautamjajoo** [comment]
@aka-jain I was just going through the website.. I figured it out so I thought just to make some change!!

**Comment by aka-jain** [comment]
So, please first open an issue and then we will decide to go with that issue or not. Hope you understand. 

Open an issue for this please.

**Comment by RishabhJain2018** [comment]
@gautamjajoo I also agree with @aka-jain . You need to open an issue for this and then discuss if we are ready to work with it or not and then after discussion you can open a pull a request. This is basically how we work.
Moreover, can you please paste the screenshots of the changes that you have done.

**Comment by aka-jain** [comment]
Yes @gautamjajoo your PR looks good. Just revert it and do the minor changes. Then we will merge it.

**Comment by deshraj** [comment]
I think @aka-jain is talking about the change that I suggested above here (https://github.com/Cloud-CV/EvalAI/pull/1454#discussion_r161266834).

**Comment by aka-jain** [comment]
Looks good. Merging it.

**Pull request merged**
