### PR TITLE
Fix: dashboard header issue on small screen devices(<480px)

### PR DESCRIPTION
**Pull request by spyshiv**
Fix for Issue #250 
@aka-jain : Please review

### CODE REVIEW

**Comment by aka-jain** [comment]
@spyshiv : Great :)
@deshraj : LGTM, please merge it.

**Comment by deshraj** [comment]
@spyshiv can you open the PR to new-ui branch instead of master?

**Comment by aka-jain** [comment]
@deshraj : it's not for new UI. You can merge this.

**Comment by deshraj** [comment]
Cool.

**Pull request merged**
