### PR TITLE
Feature to show the authentication token to the user on the MyProfile Page in EvalAI.

### PR DESCRIPTION
**Pull request by isht3**

### CODE REVIEW

**Comment by deshraj** [comment]
The button color seems odd to me. Can you please change it to the button color that we have in other places? @aka-jain do you have some suggestions for this?

**Comment by deshraj** [comment]
Also, can you add a button to copy the token to clipboard?

**Comment by isht3** [comment]
@deshraj @spyshiv  I've updated the color. But, I have this weird problem with the `ngclipboard` https://clipboardjs.com/#example-target It isn't copying the content of the variable. I suspect it's because I'm not listing the directive somewhere. Can you just check if I'm doing that right?

**Comment by spyshiv** [comment]
@isht3 you've missed. installation of `clipboard.js` before `ngclipboard`. Please follow these steps
* `npm install clipboard --save`
* Add path `node_modules/clipboard/dist/clipboard.min.js` in `app.script.json` before `ngclipboard`
* Add dependency `ngclipoard` in `app.js`

Let me know in case of anything

**Comment by isht3** [comment]
@spyshiv Thanks a tonne. It works now! :D

**Comment by isht3** [comment]
@RishabhJain2018 I did! How do I increase the width? I tried tweaking `width` it didn't work.

**Comment by RishabhJain2018** [comment]
@isht3 Yes, you have to improve the css.

**Comment by isht3** [comment]
@RishabhJain2018 I've made the changes. :)

**Comment by isht3** [comment]
@RishabhJain2018 I've added the download json feature.

**Comment by isht3** [comment]
@RishabhJain2018 I've made the changes. Should I split this into 2 different PRs?

**Comment by RishabhJain2018** [comment]
Yes.

**Comment by isht3** [comment]
Okay. I'm closing this PR.

**Pull request closed without merging**
