### PR TITLE
Added alert for the 'Show Analysis' button

### PR DESCRIPTION
**Pull request by sayamkanwar**
On the Challenge Analytics Home page, if the user has not hosted any challenges before and tries to click the “Show Analysis” button, an alert is displayed which tells the user that there are currently no challenges to be analysed.

### CODE REVIEW

**Comment by deshraj** [comment]
@sayamkanwar: thanks for opening the pull request. Can you please share the screenshot here on this thread ?

**Comment by gautamjajoo** [comment]
@sayamkanwar "The Show Analytics" button is disabled when there are no challenges to analyse.

**Comment by RishabhJain2018** [comment]
Hey @sayamkanwar Can you please paste the screenshot here.

**Comment by sayamkanwar** [comment]
screenshot 2018-11-06 at 8 48 21 pm
@RishabhJain2018

**Comment by gautamjajoo** [comment]
@sayamkanwar Yeah I know that. I was just telling that currently the button is disabled if there are no changes. We could do that remove the disability feautre and add this as the mentors say. Because both cannot work simultaneously.

**Comment by erikaaatan** [comment]
@gautamjajoo Your PR was merged before all of the instances for this task were used, which is why @sayamkanwar 's change is fine.

**Comment by gautamjajoo** [comment]
Closing this since we have already disabled the button when there are no challenges. Hence, this would not be needed. Thank you for the contribution!

**Pull request closed without merging**
