### PR TITLE
Remove stars from challenge-list page

### PR DESCRIPTION
**Pull request by gautamjajoo**
This PR removes the stars function from `challenge-card` component from `challenge-list` page.
This reduces the number of requests (5.5 sec to 1.5 sec though this number is based on the number of challenges I have on my local system)

@Ram81 @Kajol-Kumari

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@gautamjajoo can we please remove challenge service import and initialisation as well from [here](https://github.com/Cloud-CV/EvalAI/pull/3545/files#diff-47cb8bf9e64fcacdc8a2c15056001f6b043ac243035bb29da6bfe7ff76618aceL5), [here](https://github.com/Cloud-CV/EvalAI/pull/3545/files#diff-47cb8bf9e64fcacdc8a2c15056001f6b043ac243035bb29da6bfe7ff76618aceL84) and [here](https://github.com/Cloud-CV/EvalAI/pull/3545/files#diff-47cb8bf9e64fcacdc8a2c15056001f6b043ac243035bb29da6bfe7ff76618aceL90) as we aren't using it anywhere in this component? 

Also the `apiService` and `route` initialisation is redundant as we aren't using it anywhere. so please remove them from constructor and related places.

**Comment by gautamjajoo** [comment]
@Kajol-Kumari Done the changes

**Review by Kajol-Kumari — APPROVED** [review]
LGTM 👍

**Review by Ram81 — APPROVED** [review]
LGTM

**Review by RishabhJain2018 — APPROVED** [review]

**Pull request merged**
