### PR TITLE
FIX for issue 2149 (Fix Height of form input fields)

### PR DESCRIPTION
**Pull request by singh96aman**
**This is in regard to the issue-2149: Fix Height of form input fields**

I used Vanilla JavaScript as well as Angular JS events such as ng-onchange and ng-if to trigger when to display the paragraph tags. 

The CSS feature visibility allows us to hide paragraph tags so that height remains unchanged. Please refer to changes. 

This fix also allowed me to go through the code, understand and improve it.

Requesting you to please accept the changes.
screen shot 2019-03-03 at 4 27 26 pm

### CODE REVIEW

**Comment by kurianbenoy** [comment]
@singh96aman  update the master branch. Also were you assigned to work on this issue?

**Comment by deshraj** [comment]
@singh96aman: I think it is possible without using JS code. You can tweak the css and positioning of the messages such that the input fields are not moved. Please change the code accordingly.

**Comment by geekayush** [comment]
@deshraj @singh96aman  I have already submitted a PR (#2150) regarding the CSS tweaks to fix the issue.

**Comment by singh96aman** [comment]
@deshraj 
Sure! I'll try to use angular-JS to fix it.

**Comment by RishabhJain2018** [comment]
Hi @singh96aman, @geekayush has already put up a PR for it. Please feel free to take up any other issue.

**Pull request closed without merging**
