### PR TITLE
Fixed typos for resetForm

### PR DESCRIPTION
**Pull request by anweshknayak**
https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/js/controllers/authCtrl.js#L51

### CODE REVIEW

**Comment by anweshknayak** [comment]
@spyshiv @aka-jain take a look please

**Comment by spyshiv** [comment]
@anweshknayak : great :+1: 
But next time please create an issue regarding anything you want to change. So that other contributors don't conflict with the same. And that will be great for us too.
And if you are creating an issue that means you are already assigned for that issue and that task is reserved for you. Later on you can ask for help or you can also pass that to others too if you face any problem regarding that.

**Comment by spyshiv** [comment]
Update this branch with the latest master so that i can merge this.

**Comment by anweshknayak** [comment]
@spyshiv done

**Comment by aka-jain** [comment]
Merging it.

**Pull request merged**
