### PR TITLE
correct path for custom error pages

### PR DESCRIPTION
**Pull request by jainarunarunjain**
@deshraj Please review the PR.

### CODE REVIEW

**Comment by deshraj** [comment]
@jainarunarunjain Are the errors still there on the terminal now?

**Comment by jainarunarunjain** [comment]
@deshraj No,  there is no error in terminal

**Comment by deshraj** [comment]
So, you are getting travis build error because travis doesn't run `gulp dev` and hence there is not `dist` directory. As discussed before, lets create another 404 and 500 page for django in `evalai/templates`.

**Comment by jainarunarunjain** [comment]
@deshraj Sure

**Pull request closed without merging**
