### PR TITLE
Fix Endpoint to delete message from Queue

### PR DESCRIPTION
**Pull request by vkartik97**
Receipt Handle for SQS Messages are is suitable for query parameters, so this PR fixes that issues.
Example of `receipt_handle`: 
```
AQEBSoAy8Z4nDV9IAH1gfmXn4eeyy39Bfyhk5joLQAZyVeu3Gfqu8+yHIpMRHRTUwGT5iGFn+yNNnbnZWnrxOsbHmruLP7Phk1Xs4DrmOkOpBKeFg7Aj8wvIouX/IpipmkxOIkEGo6al1WtlsUAg3wJYOTvHXBmpi+Yq0GKjLY604kHOQG1Vete/MhwJkB8n/8CQFrQROaYX3e4s4jjUJUEPeobbBkpCC9CXJG71ifJzOmEBlGX3gkvhVOra6BQoeP1w4qxoOQgbZa329RF6PYyLlJx0ZbJ9oikSXWC42cklzVWV3e3Bi9caymzHbXkVpn7iduMFeMbS26I7BhPow8iv29qDakEp5BxUZRoUCr06O6MxQ9iHm9v9txYFvXr0j7Al1WfTfk/JC75j90uOfDCRfgfHkYS6khr7U6hj2rRsD2D6C175lXw3AMf/7cI30bbk
```
The handle has slashes that will cause request not to route to correct endpoint

### CODE REVIEW

**Comment by vkartik97** [comment]
> Can you please update this corresponding function in this file: https://github.com/Cloud-CV/EvalAI/blob/master/scripts/workers/remote_submission_worker.py#L389

Should I have a new PR for this?

**Comment by RishabhJain2018** [comment]
No, please add it in the same PR.

**Comment by RishabhJain2018** [comment]
There are some failing test cases. Can you please fix them?

**Comment by vkartik97** [comment]
@RishabhJain2018 Please review

**Pull request merged**
