### PR TITLE
Fixed Error message in Sign up view

### PR DESCRIPTION
**Pull request by anweshknayak**
@aka-jain @spyshiv this should work ? I cannot test it since gulp task is breaking

### CODE REVIEW

**Comment by aka-jain** [comment]
@anweshknayak Please make your code runnable, so that it will be easy for you and us to understand. 
@spyshiv I think reset function will not work with form errors., wil you please check it once.

**Comment by spyshiv** [comment]
@aka-jain: We have to reset variables on route change that will be permanent solution. The approach of calling reset function on click will conflict Since we can't initiate `ng-click` and `ui-sref` at a time.

**Comment by aka-jain** [comment]
Agree @spyshiv , we have to undo these changes.

**Comment by anweshknayak** [comment]
@aka-jain @spyshiv what is to be done about this ?

**Comment by aka-jain** [comment]
@anweshknayak Need to close this PR. We have to do some changes regarding this.

**Pull request closed without merging**
