### PR TITLE
Resend Confirmation Email for GCI

### PR DESCRIPTION
**Pull request by abinav62**

### CODE REVIEW

**Comment by abinav62** [comment]
The Travis CI is giving me a fail, even though it is not showing an error. This means the code coverage is too low, correct?

**Comment by takitsuse** [comment]
@abinav62 Not Travis CI but flake8 is making commits failed, and that means your code is not following pep8 rules. Please use `flake8` command to see where to fix.

**Comment by pushkalkatara** [comment]
@abinav62 The text doesn't look like a button. Please display it in the next line and make it look like a button.
verify

**Comment by RishabhJain2018** [comment]
@abinav62 Can you please post an updated screenshot.

**Comment by abinav62** [comment]
image

**Comment by pushkalkatara** [comment]
Hi @abinav62 Please fix the branch with the base branch.

**Comment by KhalidRmb** [comment]
@abinav62 I think you also need to edit the permission controller to display a success message on re-sending the email. Please verify.
(Here: https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/js/controllers/permissionCtrl.js)

**Comment by abinav62** [comment]
I don't know a lot of JavaScript, and the task description doesn't say I need to use it. Is it necessary to add the success message?

**Comment by KhalidRmb** [comment]
@abinav62 It would be good if you can add it. Please go through this for reference, if you're stuck anywhere: https://github.com/Cloud-CV/EvalAI/pull/2193
Thanks.

**Comment by pushkalkatara** [comment]
@abinav62 Yes a success message would be helpful for the user to make sure he has clicked on the button. Else, a user might click it several times. Also, we can hide the button or start a timer until allowing user to repress the button. 

No problem if you are not familiar with Javascript much, feel free to ask the mentors and the community.

**Comment by pushkalkatara** [comment]
Also, please update the branch with the base branch and post a screencast of the functionality.

**Comment by abinav62** [comment]
I added the changes, but my local build of the website does not allow me to send the email. I cannot take a screenshot because of this.

**Comment by abinav62** [comment]
image

**Comment by KhalidRmb** [comment]
Looks good. @pushkalkatara @Ram81 Any comments?

**Pull request closed without merging**
