### PR TITLE
fix image resolution, add logout on mobile sidebar, and make Status float left

### PR DESCRIPTION
**Pull request by ksun0**
Tasks from Google Code-in: 
1. Images are stretching up under 'Who use EvalAI" section. Make them of constant resolution.
2. After login there is no option present for logout in sidebar (mobile). Add logout link in sidebar.
3. Status part under features challenge is not properly aligned. Make it left align.

### CODE REVIEW

**Comment by aka-jain** [comment]
@ksun0 any update?

**Comment by ksun0** [comment]
Thanks for checking in! I just got everything set up everything local -- had some trouble with python paths, postgres, and node. Also, I completed the logout button (didn't see that there were already 3 default user credentials and had trouble logging in before!). 

What does this mean: "Status part under features challenge is not properly aligned. Make it left align"? Where can I find the features challenge?

**Comment by RishabhJain2018** [comment]
@ksun0 Please check the screenshot below and also notice that there is a field `Status` , we need to left align it. Let me know if you still have doubts.
csv5

**Comment by ksun0** [comment]
hello @RishabhJain2018 @aka-jain I believe I have completed all three tasks. Let me know if I need to do anything else!

Thanks,
kevin

**Comment by ksun0** [comment]
Here are some screenshots of the changes:
screen shot 2017-12-17 at 3 07 11 pm
screen shot 2017-12-17 at 3 06 45 pm
screen shot 2017-12-17 at 3 06 10 pm

**Comment by aka-jain** [comment]
@ksun0 is your GCI task approved?

**Comment by ksun0** [comment]
@aka-jain yes it was! Thanks, and Merry Christmas!

**Comment by aka-jain** [comment]
Cool. Closing this PR as these changes have been already done.

**Pull request closed without merging**
