### PR TITLE
Fix homepage responsiveness issues

### PR DESCRIPTION
**Pull request by NSDCars5**
For Google Code-In task: https://codein.withgoogle.com/dashboard/task-instances/5065255040319488/

Issues listed in the task have been fixed.

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@NSDCars5 Can you please paste the screenshots of the changes that you have done .

**Comment by NSDCars5** [comment]
@RishabhJain2018 Screenshots are attached.

1. Partner org logo scaling





2. Logout button on homepage



3. Challenge status alignment

**Comment by aka-jain** [comment]
Yeap, looks good to me. Merging it.

**Comment by aka-jain** [comment]
Closing this PR as we need to add further changes regarding responsiveness.

**Pull request closed without merging**
