### PR TITLE
adding answered file fron GCI Task

### PR DESCRIPTION
**Pull request by mmaul8**
IMPORTANT NOTES (please read, then delete):

* The PR title should start with "Fix #bugnum: " (if applicable), followed by a clear one-line present-tense summary of the changes introduced in the PR. For example: "Fix #bugnum: Introduce the first version of the collection editor.".

* Please make sure to mention "#bugnum" somewhere in the description of the PR. This enables GitHub to link the PR to the corresponding bug.

Please also make sure to follow the [style rules](https://github.com/Cloud-CV/EvalAI/blob/master/.github/CONTRIBUTING.md#style-rules).

### CODE REVIEW

**Comment by Suryansh5545** [comment]
@mmaul8 You have to push the whole repository not a simple answer page and also please put a description of what you have done and if GCI task then a link to it.

**Comment by mmaul8** [comment]
GCI task dosen't appear to submit on github page or create PR. But the GCI
mentor from CloudCV ask me to submit PR on EvalAI repo for submit my work

Pada tanggal Sen, 20 Jan 2020 3:34 PM, Suryansh pathak <
notifications@github.com> menulis:

**Comment by Suryansh5545** [comment]
@mmaul8 i think you don't understand it . See if you are asked to change something in the auth.html page of a repository then you have to edit it in the repository which you will clone or pull from git and then save the changes commit and push it. and also please add a proper title & discription which tells what this pr is for.

**Comment by RishabhJain2018** [comment]
Closing this since it is not required.

**Pull request closed without merging**
