### PR TITLE
Frontend: Allow console debug statement in development

### PR DESCRIPTION
**Pull request by spyshiv**
Fix for #956 

* Change eslint's `no-console` error to warning
* Dev server will stop only for lint errors not for warnings

@deshraj / @aka-jain Please review

### CODE REVIEW

**Comment by deshraj** [comment]
@spyshiv: As you mentioned in the previous conversation, it is not working properly with Auth. Controller. Can we get it fixed for auth controller before merging it in master?

**Comment by aka-jain** [comment]
Have you got any solution for this @spyshiv ?

**Comment by spyshiv** [comment]
@deshraj : This is very strange. Something went wrong with `authCtrl.js`. On line 12 if you check for the code block of function `AuthCtrl` by clicking beside curly brace `{` it is not showing where the block is ending. 
@aka-jain : Please check this on your system too.

**Comment by deshraj** [comment]
Yeah agree. @aka-jain can you try this on your machine and see what is the issue exactly. We might be missing something.

**Comment by aka-jain** [comment]
Will do it by today.

**Comment by aka-jain** [comment]
Got the solution @spyshiv @deshraj . There is a comment line of eslint present in auth controller which is restricting the lint to catch console as a warning. 

I've removed that line, please review it again.

**Comment by deshraj** [comment]
@spyshiv: can you please review this?

**Comment by spyshiv** [comment]
@aka-jain : Thanks for the debugging. LGTM :+1: 
@deshraj : Now things are working fine. Please merge this PR.

**Comment by deshraj** [comment]
Looks good now. Merging this.

**Pull request merged**
