### PR TITLE
Adding tags to challenges 

### PR DESCRIPTION
**Pull request by anilchoudary**

### CODE REVIEW

**Comment by Ram81** [comment]
@anilchoudary can you please fix the failing travis build for your PR before I review it.

**Comment by anilchoudary** [comment]
> @anilchoudary can you please fix the failing travis build for your PR before I review it. And please add valid description for the change too.

It works fine in my local environment. I dont understand why the build is failing here. Will resolve it quickly

**Comment by Ram81** [comment]
@anilchoudary you can see the travis ci logs here https://travis-ci.org/github/Cloud-CV/EvalAI/builds/745346753#L260. Flake8 checks are failing and there are conflicting migrations too.

**Comment by Ram81** [comment]
Closing the PR due to inactivity

**Pull request closed without merging**
