### PR TITLE
Add edit terms&conditions to settings tab 

### PR DESCRIPTION
**Pull request by gautamjajoo**
Added the edit `terms and conditions` to the settings tab under the edit challenge card.
@Ram81 @Kajol-Kumari 

Screenshot from 2021-06-16 13-11-34

### CODE REVIEW

**Comment by Ram81** [comment]
Screen Shot 2021-06-19 at 8 13 49 PM

@gautamjajoo when I switch to settings page and refresh I am seeing following message. Can you fix it.

**Comment by gautamjajoo** [comment]
@Ram81 This error is regarding the worker logs

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@gautamjajoo The `close participation` option is going below the challenge image. can we please keep all the edit options on the right side of the challenge's image. Maybe You can try keeping the `close participation` and `published` option in the same row.

Please see the ss below for ref -
Screenshot 2021-06-24 at 2 42 06 PM

**Comment by gautamjajoo** [comment]
@Kajol-Kumari Done the changes!

**Comment by gautamjajoo** [comment]
Screenshot from 2021-06-26 13-20-13

**Comment by Kajol-Kumari** [comment]
@gautamjajoo can we please make the upload button's ui similar to ⬇️ 
Screenshot 2021-06-26 at 1 47 27 PM

**Comment by gautamjajoo** [comment]
@Kajol-Kumari Done
Screenshot from 2021-06-26 14-13-53

**Review by Kajol-Kumari — APPROVED** [review]
LGTM 👍

**Review by Ram81 — APPROVED** [review]
LGTM

**Pull request merged**
