### PR TITLE
Write tests for scale_workers in aws_utils

### PR DESCRIPTION
**Pull request by daniel22373**
I wrote 3 tests that cover all of the failure scenarios addressed in scale_workers. This pull request is based off of the following GCI task:

"The test should cover all the corner cases to ensure that the function does not break for any input. You can find the codebase for the function in this file: (https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/aws_utils.py) For reference, you may use this: https://github.com/Cloud-CV/EvalAI/pull/2413/files"

### CODE REVIEW

**Comment by daniel22373** [comment]
Hello, I'm having a bit of trouble with the second test. I received the following error message:

"AssertionError: {'count': 0, 'failures': [{'message': 'Please scale[270 chars]08}]} != {'count': 2, 'failures': [{'message': 'Please scale[70 chars]07}]}
E   Diff is 667 characters long. Set self.maxDiff to None to see it."

How do I make sure the num_of_tasks parameter is only equal to the number of workers for the second challenge? I think that is the issue, please correct me if I am wrong. Also, I do not want to copy @KhalidRmb 's work, so I try to refrain from looking at his code. Thank you.

**Comment by KhalidRmb** [comment]
Hey, you can close this PR, since work has already been done on this. And take up another task. Thanks!

**Comment by takitsuse** [comment]
Hi @KhalidRmb, It is not rare that multiple people work on one task which has multiple instances. What I ask you is to increase the number of instances of this task so that not only @daniel22373 but also I can work on this task. Thanks!

**Comment by daniel22373** [comment]
Hi @Takitsuse , I am not sure where your original comment is, but thank you for the support! @KhalidRmb , since I have already put effort into this task, I would appreciate being able to keep working on it (so I can learn more from this opportunity) or get credit for my work (by having it approved). If not, that's perfectly fine. I'll close the PR, submit the task for review, and start working on another issue for now.

**Comment by KhalidRmb** [comment]
Yes, in fact a few points are missing from this. Since, @takitsuse was working on this since long before you, you can pick any other task. It won't hurt your chances to abandon this. Thanks!

**Pull request closed without merging**
