### PR TITLE
Fix #3127: Add docs for leaderboard jobs-api

### LINKED ISSUE #3127: Add swagger api documentation for get_all_entries_on_public_leaderboard API
### Description

Hosts can use EvalAI APIs to get details of the leaderboard entries. The get leaderboard entries API documentation is missing documentation on EvalAI [docs](http://eval.ai/api/docs/).

### Deliverables
Add documentation for using `get_all_entries_on_public_leaderboard` API using swagger. An example of using swagger for API documentation is available [here](https://github.com/Cloud-CV/EvalAI/blob/master/apps/jobs/views.py#L87). The documentation should provide a list of query and header params described briefly and an example.

### PR DESCRIPTION
**Pull request by burnerlee**
Add swagger api documentation for get_all_entries_on_public_leaderboard API

### CODE REVIEW

**Comment by burnerlee** [comment]
@Ram81  @RishabhJain2018 ping for PR review

**Review by RishabhJain2018 — CHANGES_REQUESTED** [review]
@burnerlee Can you please add the screenshot of the documentation from your local.

**Comment by burnerlee** [comment]
Screenshot from 2021-01-16 07-42-24
Screenshot from 2021-01-16 07-42-38
Screenshot from 2021-01-16 07-42-46

**Comment by burnerlee** [comment]
@RishabhJain2018

**Review by RishabhJain2018 — APPROVED** [review]

**Comment by RishabhJain2018** [comment]
LGTM :) Thanks for the fix @burnerlee. We will merge it once the build completes. Please feel free to take up another issue.

**Pull request merged**
