### PR TITLE
Added image and favicon

### PR DESCRIPTION
**Pull request by aka-jain**
@deshraj I'm merging this PR.

### CODE REVIEW

**Comment by the-dagger** [comment]
@aka-jain You seem to have committed a sqlite-db file too.
Do we need it?

**Comment by deshraj** [comment]
Good catch @the-dagger. @aka-jain can you please remove that file before merging?

**Comment by aka-jain** [comment]
Thanks @the-dagger for pointing this out.

**Comment by aka-jain** [comment]
@deshraj review and merge this please.

**Pull request merged**
