### PR TITLE
Fix:#2602 Added The Dark Theme

### PR DESCRIPTION
**Pull request by Suryansh5545**
#2602 
I have added the option for changing the theme a toggle button. i have changed the margins and padding of some container as they were not looking good. also some organisation images weren't good looking in dark mode so i redesigned them. 
Selection_044
Selection_043
Selection_042
Selection_041
Selection_040
Selection_039
Selection_038
Selection_037
Selection_036
Selection_035
Selection_034
Selection_033
Selection_032
Selection_045

But i want unable to change the default colour of the placeholders generated by md-container which makes some selecting elements disappear. example in below image the select phase option is not visible 
Selection_046

**Also As i am a human i by mistakely could have left a page unedited. So please let me know if you found any. Also Please Share your valuable opinion**

### CODE REVIEW

**Comment by Suryansh5545** [comment]
@Sanji515 @RishabhJain2018 @Ram81 @KhalidRmb @yashdusing @deshraj  Sir, Please take a look

**Comment by Suryansh5545** [comment]
@Sanji515 @RishabhJain2018 if the above design is good then should I proceed to add this to ngx version also??

**Comment by Suryansh5545** [comment]
@RishabhJain2018 , Sir if this feature is good then should I proceed to add it in ngx also??

**Comment by Suryansh5545** [comment]
@Ram81 @RishabhJain2018 @Sanji515 I think the lower participation of community indicates that this feature might not be required for now so should I close it?

**Comment by RishabhJain2018** [comment]
Hi @Suryansh5545, Thanks a lot for the effort. Yes, this isn't the priority, for now, so we can close it and can revisit it later.

**Pull request closed without merging**
