### PR TITLE
Fix:Added Status option in Submission Model(#406)

### PR DESCRIPTION
**Pull request by Ram81**

### CODE REVIEW

**Comment by Ram81** [comment]
@deshraj  #406 resolved please review.

**Comment by deshraj** [comment]
Looks good.

**Comment by Ram81** [comment]
@deshraj  is there any other issue I can work on?

**Comment by TroJan** [comment]
@Ram81 : please create a migration for the above. You can create migrations by running 
```
python manage.py makemigrations jobs --name=status_option_submission --settings=settings.dev
```

the value of name(`status_option_submission`) need not necessarily be the same. you can write it what ever you want, but make sure that it is something meaningful and signifies that what it is doing

**Comment by Ram81** [comment]
@TroJan  I added migration named (submitting_status_option) should I push that ,if it seems right to you?

**Comment by deshraj** [comment]
Yup, please do that.

**Comment by Ram81** [comment]
@deshraj  Done :+1:

**Pull request merged**
