### PR TITLE
Fix #842: Reload Worker whenever Challenge or Challenge Phase file changes.

### LINKED ISSUE #840: Add support in submission worker to update file field changes for Challenge and Challenge Phase
__Problem__

If the Challenge Host updates any of `evaluation_script` or `test_annotation` file, then there is no way to propagate that change to the worker.

__Please be more clear__ ?

Presently the submission worker when starts fetches all the active challenges and loads `evaluation_script` for each challenge. It also fetches active challenge phase for each challenge and loads `test_annotation` for each phase. We need to extend that code to add support for handling update requests for these files.

__Why__ ?

Imagine a case where in a Challenge Hosts whose challenge is active and hence running, wants to update `evaluation_script` for a challenge. He logs in and updates the file but still sees that submission are being processed using the older version of `evaluation_script`. He wonders why is this happening ??

So we want to help him and add support to propagate the changes done by him to the worker, because it is the worker who is doing the heavy task of processing submission.

__Impact__ ?

It actually guarantees that whenever any submission is evaluated, it is evaluated against the write set of parameters.

__How__ ?

Overall, this will involve refactoring `scripts/workers/submission_worker.py`. The concerned function which extracts challenge and phase data presently is `extract_challenge_data`. This function may be modified or a new function may be added. This will actually require some **thoughts** from the contributor.

One very important thing which needs to be pointed out is how the worker will detect that the file is changed. Here RabbitMQ comes into action. If you see `add_challenge_queue` in `scripts/workers/submission_worker.py`, it binds on key `challenge.*.*`. The first `*` here will help us decide what the intent of the message is. 

Whenever any new challenge will be added, you can assume that `challenge.add.*` key will be there and whenever any update is done, you can assume that `challenge.edit.*` will be published.

So you can now add checks according to the key and then code accordingly.

For now being you can assume that keys published will be `challenge.add.*` and `challenge.edit.*`.

__TakeAways__

About how the submission worker works in detail, RabbitMQ and its related terminologies. This issue will provide you more depth about RabbitMQ and how queue function.

Also I will prefer that before coding, its better to discuss the approach over here only, so that we can get an idea and update if something is not right.

### LINKED ISSUE #841: Publish message whenever file field of Challenge and Challenge Phase changes
__Problem__

We need to propagate changes related to `test_annotation` and `evaluation_script` to the submission worker. The support for handling the change already in the worker is being taken care of in [Issue 840](https://github.com/Cloud-CV/EvalAI/issues/840). We need to add support for publishing message when ever any such change happens.

__Please be more clear__ ?

When ever `evaluation_script` or `test_annotation` file of Challenge or ChallengePhase changes, we need a way to tell this to submission worker that the files have changed and you need to update the files.

The best way can be by using a Queue based architecture and publishing a message to the exchange.

__Why__ ?

Submission worker when starts loads all `evaluation_script` and `test_annotation` file in advance. In case if the Challenge Host updates any of the file, there is no way to communicate this to the worker.

If the worker is not communicated about the changes, then submissions may be evaluated with the wrong set of parameters.

__Impact__ ?

It actually guarantees that whenever any submission is evaluated, it is evaluated against the write set of parameters.

__How__ ?

It can be done by capturing the update of concerned models(here _Challenge_ and _ChallengePhase_).
[Issue 839](https://github.com/Cloud-CV/EvalAI/issues/839) deals with this. The print statement in that issue can now be modified and there a new message can be published.

The __content__ of the message still needs to be figured out by the __contributor__. I will prefer that you publish only primary keys in the message but this is still open to discussion.

Regarding how to publish message, you can take help from function `publish_submission_message` of `jobs/sender.py`. The published message will have a routing key of `challenge.edit.*`.

__TakeAways__

How Exchanges work in RabbitMQ, how message are routed to the exchange ?

Also I will prefer that before coding, its better to discuss the approach over here only, so that we can get an idea and update if something is not right.

### LINKED ISSUE #842: Add support to reload worker whenever Challenge or Challenge Phase file changes
Description: The worker when starts loads all the active challenges and challenge phase. It fetches `evaluation_script` for Challenge and `test_annotation` for Challenge Phase and stores them on disk.

Now if the Challenge Host updates any of these files, then should be reflected in the worker also.

We need to add support for this

It is a big issue, Hence it will involve many sub-issues

- [ ] Log change in Challenge and Challenge Phase model when file fields are updated, Issue [839](https://github.com/Cloud-CV/EvalAI/issues/839)
- [ ] Add support in submission worker to update file field changes for Challenge and Challenge Phase, Issue [840](https://github.com/Cloud-CV/EvalAI/issues/840)
- [ ] Publish message whenever file field of Challenge and Challenge Phase changes, Issue [841](https://github.com/Cloud-CV/EvalAI/issues/841)

Note: This issue on its own does not require any coding, Just that it will help us to track the progress  of individual sub-issues and have a broader picture here.

### PR DESCRIPTION
**Pull request by isht3**
* Add support for submission worker to update file field changes for
       Challenge and Challenge Phase, Issue 840

  * Publish message whenever file field of Challenge and Challenge Phase
       changes, Issue 841.

Fixes #842, Fixes #841, Fixes #840

### CODE REVIEW

**Comment by isht3** [comment]
Hi! I won't be available for a few days, do let me know if any changes need to be made. :smile:

**Comment by deshraj** [comment]
Thanks @isht3 for the fix. I went through the pull request but I am not exactly sure if I follow the code. Would you mind adding docstring to each of the methods that you have created?

**Comment by isht3** [comment]
@deshraj I have added the docstring to the PR. Please review it. :smile:

**Comment by isht3** [comment]
@deshraj @RishabhJain2018 Can you review this? 😄

**Comment by deshraj** [comment]
@isht3: Sorry, I was busy with other stuff. I will review this pull request in few hours. Also, you might want to start thinking about how to write tests for the code that you have added in this pull request (which is beyond the scope of this pull request but we really need it).

**Comment by isht3** [comment]
@deshraj So I'm guessing running a `submission_worker` tests a `--sw` flag can be sent to the `python manage.py test --sw --settings=settings.dev` and these tests can be run as a different process. As taranjeet mentioned in #1005 using subprocess to start the script will be a good way of doing it, right? I'll get started as soon as the implementation of the tests are finalised here and will open it as another PR. Also I've send you an idea on submissions on gitter, could you also give me feedback on that? Thanks! :smile:

**Comment by isht3** [comment]
@deshraj Other option is to not use RabbitMQ server and we can use a mock server and do the tests there.
Somthing like, 

```
class FakePublisher(Publisher)
    def __init__(self):
        pass
    def call_consumer(self, msg):
        self.consumer(msg)

class test(unittest.TestCase):
    def test_foo(self):
        publisher = FakePublisher()
        ret = publisher.call_consumer(msg("foo"))
        self.assertEqual(ret, True)
```

Here, you can mock a RabbitMQ server without running RabbitMQ and we will be able to test the `submission_worker` along with the rest of the test  suite.

**Comment by isht3** [comment]
Do let me know which option should be used for this and I'll get started with the issue.

**Comment by deshraj** [comment]
Mock server sounds like a great idea. We should totally do that. I have commented on the relevant pull request as well. Let me know if you have doubts or need to discuss something about the same.

**Comment by RishabhJain2018** [comment]
Since, we aren't using RabbitMQ now. Hence, I'm closing this issue.

**Pull request closed without merging**
