### PR TITLE
Setup Sphinx Documentation

### PR DESCRIPTION
**Pull request by AnshulBasia**
@deshraj Please have a look. I have completed all the to-dos you mentioned. Last to-do is with the last commit. I moved the old files in docs/old files and it also contains doctrees and html for those files. Feel free to delete them. I did not want to explicitly delete anything. Suitable files were added to toc-tree and required html files and doctrees and located in docs/_build. Feel free to tell me if there's any issue with this PR. Thanks for your time.

#854

### CODE REVIEW

**Comment by AnshulBasia** [comment]
Please check the folder docs/sphinx documentation , for some reason, I was not able to push the folder 'docs/_build' and I don't know why the commit 'submission app deleted' is still being in this PR which has already been merged. Inconvenience regretted :(

**Comment by AnshulBasia** [comment]
@deshraj  Please let me know if you want me to create a new PR, in case there's any issue with it.

**Comment by deshraj** [comment]
@AnshulBasia Sorry I didn't get time since I was travelling. I will review it soon and will merge it.

**Comment by AnshulBasia** [comment]
@deshraj  Not a problem. Just let me know :)

**Comment by deshraj** [comment]
@AnshulBasia is there any specific reason for having `docs/old files/` or if this is not required, then can you please remove it?

**Comment by AnshulBasia** [comment]
@deshraj  Done!!

**Comment by deshraj** [comment]
@AnshulBasia I am not sure why there an extra level of directory `docs/sphinx_documentation`. We might just set the configuration in such a way that all the docs are built in `docs/` and not in `docs/sphinx_documentation`. Please let me know if I am not clear.

**Comment by AnshulBasia** [comment]
For some reason, I was not able to commit with folder named '_build',
that's why I did that.

Thanks
Anshul

**Comment by taranjeet** [comment]
@deshraj @AnshulBasia : is this still required? If yes can we fix it and get it released soon?

**Comment by deshraj** [comment]
Closing this one since @taranjeet is already setting this up from scratch. Thanks @AnshulBasia for your support. :)

**Pull request closed without merging**
