### PR TITLE
Add required fields for meta attributes

### PR DESCRIPTION
**Pull request by Ram81**
### Description

Required check for radio buttons and checkbox was not working for submission meta Attributes as the md-radio-group issue hasn't been fixed by angular [yet](https://github.com/angular/material/issues/1305). This PR adds a validation check

### CODE REVIEW

**Review by RishabhJain2018 — APPROVED** [review]

**Review by RishabhJain2018 — CHANGES_REQUESTED** [review]
@Ram81 On the UI, can we please add `*` in front of the fields which are required?

**Comment by RishabhJain2018** [comment]
Can you please paste the UI screenshot here?

**Comment by Ram81** [comment]
Screen Shot 2020-10-10 at 11 09 51 PM

**Comment by RishabhJain2018** [comment]
Can we please make the `*` color to orange.

**Comment by Ram81** [comment]
Screen Shot 2020-10-10 at 11 17 51 PM

**Review by RishabhJain2018 — APPROVED** [review]

**Pull request merged**
