### PR TITLE
Add team in ParticipantAdmin class in Participant app

### PR DESCRIPTION
**Pull request by gauthamzz**

### CODE REVIEW

**Comment by gauthamzz** [comment]
@deshraj can u see

**Comment by deshraj** [comment]
@gauthamzz Can you please remove the ParticipantAdmin part from this PR since @jainarunarunjain was already working on this. Please make sure that if someone is already working on some issue then don't make PR for that. There are a lot of issues to work on. :-)

**Comment by gauthamzz** [comment]
my bad i didnt see it

**Comment by deshraj** [comment]
It's ok. :-)

**Pull request closed without merging**
