### PR TITLE
Update EvalAI Users List 

### LINKED ISSUE #1887: Update EvalAI Users List
Deliverables:

- [ ] Add HD logo for Ebay 
download

- [ ] Add HD logo for IIT Madras
1200px-iit_madras_logo svg

- [ ] Add HD logo for University Of Adelaide
the-university-of-adelaide-1-logo-png-transparent

### PR DESCRIPTION
**Pull request by gautamjajoo**
Fixes #1887 . I have used new logo of eBay, because the original one had white background.
@deshraj @RishabhJain2018 
capture

### CODE REVIEW

**Comment by deshraj** [comment]
@gautamjajoo can you please share the screenshot of the mobile view? Thanks!

**Comment by gautamjajoo** [comment]
capture

**Comment by deshraj** [comment]
Thanks Gautam. I can merge this but do you want to work on resizing the images to the same size so that they look consistent. Currently, it looks odd since different images have different size. We can count that as a GCI task if you do that well. :)

**Comment by gautamjajoo** [comment]
@deshraj Ok. I will work on that.

**Comment by deshraj** [comment]
Thanks @gautamjajoo :)

**Comment by gautamjajoo** [comment]
@deshraj So, I should open a new PR for the consistency of images.

**Comment by deshraj** [comment]
Yeah, a separate PR would be great.

**Pull request merged**
