### PR TITLE
Fix #1800 Loads challenge data at challenge creation

### LINKED ISSUE #1800: Load challenge data in the process when challenge is created
## Description

Currently, when someone creates a challenge on EvalAI, then gets the access to make submissions to that challenge in order to test it. But the catch here is that the submission worker is not ready to accept the submissions for that challenge since it needs to load the evaluation script and other required files. Hence whatever submission the challenge host does, it stays in the submitted state.

## How to fix it

- [ ] Add support for loading the required challenge related files whenever the challenge is created making sure that submission worker is reloaded or is loading the required files in memory

### PR DESCRIPTION
**Pull request by TejasBhitle**
This issue (#1800) was fixed with introducing a new type of message 'add challenge message' in the queue. This message is published in the queue at the time of challenge creation.

### CODE REVIEW

**Comment by TejasBhitle** [comment]
Sure. I'll rebase my branch and push again.

**Comment by TejasBhitle** [comment]
@RishabhJain2018 I have rebased my branch. Thanks for the documentation for git rebase and merge.
Can you please verify if commit history is proper as well as review my changes ?

**Comment by TejasBhitle** [comment]
@RishabhJain2018 Can you please review this PR ?

**Comment by RishabhJain2018** [comment]
@TejasBhitle Thanks for the PR. Can you please describe it briefly how it is solving the issue?

**Comment by deshraj** [comment]
Closing due to inactivity.

**Pull request closed without merging**
