### PR TITLE
Fix grammatical mistakes in EvalAI docs

### PR DESCRIPTION
**Pull request by HizkiFW**
PR for a Google Code-In task.

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@HizkiFW can please resolve the conflicts.

**Comment by HizkiFW** [comment]
@RishabhJain2018 I've merged the `master` branch into mine and resolved the conflicts 6b7ad34b81c4ad01b344a52c5927049d40665cb1.

**Comment by deshraj** [comment]
@HizkiFW seems like the conflict is not resolved. You can use Github UI to resolve the conflicts. Please let us know if you are not able to do that. We would be happy to help.

**Comment by HizkiFW** [comment]
@RishabhJain2018 It appears that some more changes have been made to the `master` branch. Last night, after I've clicked the <kbd>Resolve conflicts</kbd> button, the checks say

>This pull request can be automatically merged by project collaborators

I've now fixed the conflicts again. Please recheck. Thanks!

**Comment by HizkiFW** [comment]
Yeah, I just checked back here, and there were conflicts in the commits. Other people keep on modifying the doc, and I can't stay awake all night resolving the conflicts; so just letting you know that I've resolved the conflicts for now.

image

**Comment by HizkiFW** [comment]
@RishabhJain2018 I've added a commit to fix the issues. Please take a look, thanks!

**Pull request merged**
