### PR TITLE
Fix challenge template page component

### PR DESCRIPTION
**Pull request by gautamjajoo**
Added footer on challenge template page and also fix the page.
@Ram81 @Kajol-Kumari 

The side bar is working fine, the screenshot was not captured correctly.
screencapture-0-0-0-0-4200-template-challenge-create-2-1-2021-07-14-19_56_20

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@gautamjajoo Can we please fix the following
1. The heading `Create Challenge` font and padding isn't consistent with the other pages heading.
2. The `Challenge Phases` part should look like a sub-heading having standard margin.
3. When we hover over the calendar icon, my cursor should change to pointer indicating that it's a clickable icon.

**Comment by gautamjajoo** [comment]
@Kajol-Kumari Done the changes:

screencapture-0-0-0-0-4200-template-challenge-create-1-1-2021-07-17-20_43_39

**Review by Kajol-Kumari — APPROVED** [review]
LGTM 👍

**Review by Ram81 — APPROVED** [review]
LGTM

**Pull request merged**
